// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.20336
//    <NameSpace>TechnoLogica.RegiX.NCPRMedicinalProductsAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.NCPRMedicinalProductsAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class ATCCodesType {
        
        private List<string> aTCCodeField;
        
        /// <summary>
        /// ATCCodesType class constructor
        /// </summary>
        public ATCCodesType() {
            this.aTCCodeField = new List<string>();
        }
        
        /// <summary>
        /// Анатомо-терапевтичен код /ATC-код/
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("ATCCode", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Анатомо-терапевтичен код /ATC-код/")]
        public List<string> ATCCode {
            get {
                return this.aTCCodeField;
            }
            set {
                this.aTCCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductType {
        
        private long registerMedicamentIdField;
        
        private bool registerMedicamentIdFieldSpecified;
        
        private long medicinalProductIdentifierField;
        
        private bool medicinalProductIdentifierFieldSpecified;
        
        private string registerCodeField;
        
        private string registerNameField;
        
        private string nameBGField;
        
        private string nameENField;
        
        private string iNNField;
        
        private ATCCodesType aTCCodesField;
        
        private string authorizationHolderField;
        
        private string producerField;
        
        private string medicamentFormField;
        
        private string quantityField;
        
        private string medicamentUnitField;
        
        private string finalPackField;
        
        private decimal merchantFinalPriceBGNField;
        
        private bool merchantFinalPriceBGNFieldSpecified;
        
        private decimal retailerFinalPriceBGNField;
        
        private bool retailerFinalPriceBGNFieldSpecified;
        
        private System.DateTime publishedAtField;
        
        private bool publishedAtFieldSpecified;
        
        /// <summary>
        /// MedicinalProductType class constructor
        /// </summary>
        public MedicinalProductType() {
            this.aTCCodesField = new ATCCodesType();
        }
        
        /// <summary>
        /// Регистров номер на медикамента
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Регистров номер на медикамента")]
        public long RegisterMedicamentId {
            get {
                return this.registerMedicamentIdField;
            }
            set {
                this.registerMedicamentIdField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegisterMedicamentIdSpecified {
            get {
                return this.registerMedicamentIdFieldSpecified;
            }
            set {
                this.registerMedicamentIdFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Национален номер за идентификация на ЛП
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Национален номер за идентификация на ЛП")]
        public long MedicinalProductIdentifier {
            get {
                return this.medicinalProductIdentifierField;
            }
            set {
                this.medicinalProductIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MedicinalProductIdentifierSpecified {
            get {
                return this.medicinalProductIdentifierFieldSpecified;
            }
            set {
                this.medicinalProductIdentifierFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Уникален код на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Уникален код на регистър")]
        public string RegisterCode {
            get {
                return this.registerCodeField;
            }
            set {
                this.registerCodeField = value;
            }
        }
        
        /// <summary>
        /// Наименование на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Наименование на регистър")]
        public string RegisterName {
            get {
                return this.registerNameField;
            }
            set {
                this.registerNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на лекарствен продукт (BG)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Наименование на лекарствен продукт (BG)")]
        public string NameBG {
            get {
                return this.nameBGField;
            }
            set {
                this.nameBGField = value;
            }
        }
        
        /// <summary>
        /// Наименование на лекарствен продукт (EN
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Наименование на лекарствен продукт (EN")]
        public string NameEN {
            get {
                return this.nameENField;
            }
            set {
                this.nameENField = value;
            }
        }
        
        /// <summary>
        /// Международно непатентно наименование /INN/
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Международно непатентно наименование /INN/")]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
        
        /// <summary>
        /// Анатомо-терапевтични кодове /ATC-кодове/
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Анатомо-терапевтични кодове /ATC-кодове/")]
        public ATCCodesType ATCCodes {
            get {
                return this.aTCCodesField;
            }
            set {
                this.aTCCodesField = value;
            }
        }
        
        /// <summary>
        /// Притежател на разрешение за употреба
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Притежател на разрешение за употреба")]
        public string AuthorizationHolder {
            get {
                return this.authorizationHolderField;
            }
            set {
                this.authorizationHolderField = value;
            }
        }
        
        /// <summary>
        /// Производител
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DescriptionAttribute("Производител")]
        public string Producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
            }
        }
        
        /// <summary>
        /// Лекарствена форма
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DescriptionAttribute("Лекарствена форма")]
        public string MedicamentForm {
            get {
                return this.medicamentFormField;
            }
            set {
                this.medicamentFormField = value;
            }
        }
        
        /// <summary>
        /// Количество на активното лекарствено вещество
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Количество на активното лекарствено вещество")]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <summary>
        /// Мерна единица
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DescriptionAttribute("Мерна единица")]
        public string MedicamentUnit {
            get {
                return this.medicamentUnitField;
            }
            set {
                this.medicamentUnitField = value;
            }
        }
        
        /// <summary>
        /// Окончателна опаковка
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DescriptionAttribute("Окончателна опаковка")]
        public string FinalPack {
            get {
                return this.finalPackField;
            }
            set {
                this.finalPackField = value;
            }
        }
        
        /// <summary>
        /// Цена Търговец на едро с ДДС, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DescriptionAttribute("Цена Търговец на едро с ДДС, лв.")]
        public decimal MerchantFinalPriceBGN {
            get {
                return this.merchantFinalPriceBGNField;
            }
            set {
                this.merchantFinalPriceBGNField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantFinalPriceBGNSpecified {
            get {
                return this.merchantFinalPriceBGNFieldSpecified;
            }
            set {
                this.merchantFinalPriceBGNFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цена Търговец на дребно с ДДС, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DescriptionAttribute("Цена Търговец на дребно с ДДС, лв.")]
        public decimal RetailerFinalPriceBGN {
            get {
                return this.retailerFinalPriceBGNField;
            }
            set {
                this.retailerFinalPriceBGNField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetailerFinalPriceBGNSpecified {
            get {
                return this.retailerFinalPriceBGNFieldSpecified;
            }
            set {
                this.retailerFinalPriceBGNFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Дата на настъпили промени в обстоятелствата
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DescriptionAttribute("Дата на настъпили промени в обстоятелствата")]
        public System.DateTime PublishedAt {
            get {
                return this.publishedAtField;
            }
            set {
                this.publishedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishedAtSpecified {
            get {
                return this.publishedAtFieldSpecified;
            }
            set {
                this.publishedAtFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductsType {
        
        private List<MedicinalProductType> medicinalProductField;
        
        /// <summary>
        /// MedicinalProductsType class constructor
        /// </summary>
        public MedicinalProductsType() {
            this.medicinalProductField = new List<MedicinalProductType>();
        }
        
        /// <summary>
        /// Лекарствен продукт
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MedicinalProduct", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Лекарствен продукт")]
        public List<MedicinalProductType> MedicinalProduct {
            get {
                return this.medicinalProductField;
            }
            set {
                this.medicinalProductField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductData {
        
        private long medicinalProductIdentifierField;
        
        private bool medicinalProductIdentifierFieldSpecified;
        
        private string nameBGField;
        
        private string nameENField;
        
        private MedicinalProductPDLRegistersDataType medicinalProductPDLRegistersDataField;
        
        private MedicinalProductCeilingPricesRegistersDataType medicinalProductCeilingPricesRegisterDataField;
        
        private MedicinalProductMaxPricesRegistersDataType medicinalProductMaxPricesRegisterDataField;
        
        private string iNNField;
        
        private string authorizationHolderField;
        
        private string authorizationNumberField;
        
        private string medicamentFormField;
        
        private string quantityField;
        
        private string medicamentUnitField;
        
        private string finalPackField;
        
        private string producerField;
        
        private decimal producerDeclaredPriceField;
        
        private bool producerDeclaredPriceFieldSpecified;
        
        private string producerPriceCurrencyField;
        
        private decimal producerPriceExchangeRateField;
        
        private bool producerPriceExchangeRateFieldSpecified;
        
        private decimal producerPriceField;
        
        private bool producerPriceFieldSpecified;
        
        private decimal producerVatField;
        
        private bool producerVatFieldSpecified;
        
        private decimal producerFinalPriceBGNField;
        
        private bool producerFinalPriceBGNFieldSpecified;
        
        private decimal merchantMarginPercentField;
        
        private bool merchantMarginPercentFieldSpecified;
        
        private decimal merchantMarginValueField;
        
        private bool merchantMarginValueFieldSpecified;
        
        private decimal merchantPriceNoVatField;
        
        private bool merchantPriceNoVatFieldSpecified;
        
        private decimal merchantVatField;
        
        private bool merchantVatFieldSpecified;
        
        private decimal merchantFinalPriceBGNField;
        
        private bool merchantFinalPriceBGNFieldSpecified;
        
        private decimal retailerMarginPercentField;
        
        private bool retailerMarginPercentFieldSpecified;
        
        private decimal retailerMarginValueField;
        
        private bool retailerMarginValueFieldSpecified;
        
        private decimal retailerPriceNoVatField;
        
        private bool retailerPriceNoVatFieldSpecified;
        
        private decimal retailerVatField;
        
        private bool retailerVatFieldSpecified;
        
        private decimal retailerFinalPriceBGNField;
        
        private bool retailerFinalPriceBGNFieldSpecified;
        
        /// <summary>
        /// MedicinalProductData class constructor
        /// </summary>
        public MedicinalProductData() {
            this.medicinalProductMaxPricesRegisterDataField = new MedicinalProductMaxPricesRegistersDataType();
            this.medicinalProductCeilingPricesRegisterDataField = new MedicinalProductCeilingPricesRegistersDataType();
            this.medicinalProductPDLRegistersDataField = new MedicinalProductPDLRegistersDataType();
        }
        
        /// <summary>
        /// Национален номер за идентификация на лекарствен продукт
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Национален номер за идентификация на лекарствен продукт")]
        public long MedicinalProductIdentifier {
            get {
                return this.medicinalProductIdentifierField;
            }
            set {
                this.medicinalProductIdentifierField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MedicinalProductIdentifierSpecified {
            get {
                return this.medicinalProductIdentifierFieldSpecified;
            }
            set {
                this.medicinalProductIdentifierFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Наименование на лекарствен продукт (BG)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Наименование на лекарствен продукт (BG)")]
        public string NameBG {
            get {
                return this.nameBGField;
            }
            set {
                this.nameBGField = value;
            }
        }
        
        /// <summary>
        /// Наименование на лекарствен продукт (EN)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Наименование на лекарствен продукт (EN)")]
        public string NameEN {
            get {
                return this.nameENField;
            }
            set {
                this.nameENField = value;
            }
        }
        
        /// <summary>
        /// Данни за лекарствен продукт в Позитивен лекарствен списък
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Данни за лекарствен продукт в Позитивен лекарствен списък")]
        public MedicinalProductPDLRegistersDataType MedicinalProductPDLRegistersData {
            get {
                return this.medicinalProductPDLRegistersDataField;
            }
            set {
                this.medicinalProductPDLRegistersDataField = value;
            }
        }
        
        /// <summary>
        /// Данни за лекарствен продукт в Регистър на пределните цени
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Данни за лекарствен продукт в Регистър на пределните цени")]
        public MedicinalProductCeilingPricesRegistersDataType MedicinalProductCeilingPricesRegisterData {
            get {
                return this.medicinalProductCeilingPricesRegisterDataField;
            }
            set {
                this.medicinalProductCeilingPricesRegisterDataField = value;
            }
        }
        
        /// <summary>
        /// Данни за лекарствен продукт в Регистър на максималните продажни цени
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Данни за лекарствен продукт в Регистър на максималните продажни цени")]
        public MedicinalProductMaxPricesRegistersDataType MedicinalProductMaxPricesRegisterData {
            get {
                return this.medicinalProductMaxPricesRegisterDataField;
            }
            set {
                this.medicinalProductMaxPricesRegisterDataField = value;
            }
        }
        
        /// <summary>
        /// Международно непатентно наименование /INN/
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Международно непатентно наименование /INN/")]
        public string INN {
            get {
                return this.iNNField;
            }
            set {
                this.iNNField = value;
            }
        }
        
        /// <summary>
        /// Притежател на разрешение за употреба
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Притежател на разрешение за употреба")]
        public string AuthorizationHolder {
            get {
                return this.authorizationHolderField;
            }
            set {
                this.authorizationHolderField = value;
            }
        }
        
        /// <summary>
        /// № на разрешение за употреба / Регистрационен номер
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("№ на разрешение за употреба / Регистрационен номер")]
        public string AuthorizationNumber {
            get {
                return this.authorizationNumberField;
            }
            set {
                this.authorizationNumberField = value;
            }
        }
        
        /// <summary>
        /// Лекарствена форма
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DescriptionAttribute("Лекарствена форма")]
        public string MedicamentForm {
            get {
                return this.medicamentFormField;
            }
            set {
                this.medicamentFormField = value;
            }
        }
        
        /// <summary>
        /// Количество на активното лекарствено вещество
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DescriptionAttribute("Количество на активното лекарствено вещество")]
        public string Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <summary>
        /// Мерна единица
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Мерна единица")]
        public string MedicamentUnit {
            get {
                return this.medicamentUnitField;
            }
            set {
                this.medicamentUnitField = value;
            }
        }
        
        /// <summary>
        /// Окончателна опаковка
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DescriptionAttribute("Окончателна опаковка")]
        public string FinalPack {
            get {
                return this.finalPackField;
            }
            set {
                this.finalPackField = value;
            }
        }
        
        /// <summary>
        /// Производител
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DescriptionAttribute("Производител")]
        public string Producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
            }
        }
        
        /// <summary>
        /// Цена на производител
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DescriptionAttribute("Цена на производител")]
        public decimal ProducerDeclaredPrice {
            get {
                return this.producerDeclaredPriceField;
            }
            set {
                this.producerDeclaredPriceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProducerDeclaredPriceSpecified {
            get {
                return this.producerDeclaredPriceFieldSpecified;
            }
            set {
                this.producerDeclaredPriceFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Валута на цена на производител
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DescriptionAttribute("Валута на цена на производител")]
        public string ProducerPriceCurrency {
            get {
                return this.producerPriceCurrencyField;
            }
            set {
                this.producerPriceCurrencyField = value;
            }
        }
        
        /// <summary>
        /// Обменен курс
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DescriptionAttribute("Обменен курс")]
        public decimal ProducerPriceExchangeRate {
            get {
                return this.producerPriceExchangeRateField;
            }
            set {
                this.producerPriceExchangeRateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProducerPriceExchangeRateSpecified {
            get {
                return this.producerPriceExchangeRateFieldSpecified;
            }
            set {
                this.producerPriceExchangeRateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цена на производител в лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        [System.ComponentModel.DescriptionAttribute("Цена на производител в лв.")]
        public decimal ProducerPrice {
            get {
                return this.producerPriceField;
            }
            set {
                this.producerPriceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProducerPriceSpecified {
            get {
                return this.producerPriceFieldSpecified;
            }
            set {
                this.producerPriceFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// ДДС на производител, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        [System.ComponentModel.DescriptionAttribute("ДДС на производител, лв.")]
        public decimal ProducerVat {
            get {
                return this.producerVatField;
            }
            set {
                this.producerVatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProducerVatSpecified {
            get {
                return this.producerVatFieldSpecified;
            }
            set {
                this.producerVatFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цена на производител с ДДС, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        [System.ComponentModel.DescriptionAttribute("Цена на производител с ДДС, лв.")]
        public decimal ProducerFinalPriceBGN {
            get {
                return this.producerFinalPriceBGNField;
            }
            set {
                this.producerFinalPriceBGNField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ProducerFinalPriceBGNSpecified {
            get {
                return this.producerFinalPriceBGNFieldSpecified;
            }
            set {
                this.producerFinalPriceBGNFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Надценка Търговец на едро, %
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        [System.ComponentModel.DescriptionAttribute("Надценка Търговец на едро, %")]
        public decimal MerchantMarginPercent {
            get {
                return this.merchantMarginPercentField;
            }
            set {
                this.merchantMarginPercentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantMarginPercentSpecified {
            get {
                return this.merchantMarginPercentFieldSpecified;
            }
            set {
                this.merchantMarginPercentFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Надценка Търговец на едро, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        [System.ComponentModel.DescriptionAttribute("Надценка Търговец на едро, лв.")]
        public decimal MerchantMarginValue {
            get {
                return this.merchantMarginValueField;
            }
            set {
                this.merchantMarginValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantMarginValueSpecified {
            get {
                return this.merchantMarginValueFieldSpecified;
            }
            set {
                this.merchantMarginValueFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цена Търговец на едро без ДДС, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        [System.ComponentModel.DescriptionAttribute("Цена Търговец на едро без ДДС, лв.")]
        public decimal MerchantPriceNoVat {
            get {
                return this.merchantPriceNoVatField;
            }
            set {
                this.merchantPriceNoVatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantPriceNoVatSpecified {
            get {
                return this.merchantPriceNoVatFieldSpecified;
            }
            set {
                this.merchantPriceNoVatFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// ДДС на търговец на едро, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        [System.ComponentModel.DescriptionAttribute("ДДС на търговец на едро, лв.")]
        public decimal MerchantVat {
            get {
                return this.merchantVatField;
            }
            set {
                this.merchantVatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantVatSpecified {
            get {
                return this.merchantVatFieldSpecified;
            }
            set {
                this.merchantVatFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цена Търговец на едро с ДДС, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        [System.ComponentModel.DescriptionAttribute("Цена Търговец на едро с ДДС, лв.")]
        public decimal MerchantFinalPriceBGN {
            get {
                return this.merchantFinalPriceBGNField;
            }
            set {
                this.merchantFinalPriceBGNField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MerchantFinalPriceBGNSpecified {
            get {
                return this.merchantFinalPriceBGNFieldSpecified;
            }
            set {
                this.merchantFinalPriceBGNFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Надценка Търговец на дребно, %
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        [System.ComponentModel.DescriptionAttribute("Надценка Търговец на дребно, %")]
        public decimal RetailerMarginPercent {
            get {
                return this.retailerMarginPercentField;
            }
            set {
                this.retailerMarginPercentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetailerMarginPercentSpecified {
            get {
                return this.retailerMarginPercentFieldSpecified;
            }
            set {
                this.retailerMarginPercentFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Надценка Търговец на дребно, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        [System.ComponentModel.DescriptionAttribute("Надценка Търговец на дребно, лв.")]
        public decimal RetailerMarginValue {
            get {
                return this.retailerMarginValueField;
            }
            set {
                this.retailerMarginValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetailerMarginValueSpecified {
            get {
                return this.retailerMarginValueFieldSpecified;
            }
            set {
                this.retailerMarginValueFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цена Търговец на дребно без ДДС, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        [System.ComponentModel.DescriptionAttribute("Цена Търговец на дребно без ДДС, лв.")]
        public decimal RetailerPriceNoVat {
            get {
                return this.retailerPriceNoVatField;
            }
            set {
                this.retailerPriceNoVatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetailerPriceNoVatSpecified {
            get {
                return this.retailerPriceNoVatFieldSpecified;
            }
            set {
                this.retailerPriceNoVatFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// ДДС на търговец на дребно, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        [System.ComponentModel.DescriptionAttribute("ДДС на търговец на дребно, лв.")]
        public decimal RetailerVat {
            get {
                return this.retailerVatField;
            }
            set {
                this.retailerVatField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetailerVatSpecified {
            get {
                return this.retailerVatFieldSpecified;
            }
            set {
                this.retailerVatFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Цена Търговец на дребно с ДДС, лв.
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        [System.ComponentModel.DescriptionAttribute("Цена Търговец на дребно с ДДС, лв.")]
        public decimal RetailerFinalPriceBGN {
            get {
                return this.retailerFinalPriceBGNField;
            }
            set {
                this.retailerFinalPriceBGNField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetailerFinalPriceBGNSpecified {
            get {
                return this.retailerFinalPriceBGNFieldSpecified;
            }
            set {
                this.retailerFinalPriceBGNFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductPDLRegistersDataType : medicinalProductPDLRegisterData {
        
        private List<MedicinalProductPDLRegisterDataType> medicinalProductPDLRegisterDataField;
        
        /// <summary>
        /// MedicinalProductPDLRegistersDataType class constructor
        /// </summary>
        public MedicinalProductPDLRegistersDataType() {
            this.medicinalProductPDLRegisterDataField = new List<MedicinalProductPDLRegisterDataType>();
        }
        
        /// <summary>
        /// Данни за лекарствен продукт в Позитивен лекарствен списък
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MedicinalProductPDLRegisterData", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Данни за лекарствен продукт в Позитивен лекарствен списък")]
        public List<MedicinalProductPDLRegisterDataType> MedicinalProductPDLRegisterData {
            get {
                return this.medicinalProductPDLRegisterDataField;
            }
            set {
                this.medicinalProductPDLRegisterDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductPDLRegisterDataType {
        
        private string registerNameField;
        
        private System.DateTime publishedAtField;
        
        private bool publishedAtFieldSpecified;
        
        private string registerCodeField;
        
        private string groupField;
        
        private ATCCodesType aTCCodesField;
        
        private decimal reimbursementPercentField;
        
        private bool reimbursementPercentFieldSpecified;
        
        private decimal reimbursementValueField;
        
        private bool reimbursementValueFieldSpecified;
        
        private string dDDValueField;
        
        private string dDDUnitField;
        
        private decimal dDDReferentValueField;
        
        private bool dDDReferentValueFieldSpecified;
        
        private float packDDDNumberField;
        
        private bool packDDDNumberFieldSpecified;
        
        private bool isDddWHOField;
        
        private bool isDddWHOFieldSpecified;
        
        private decimal packPriceRefDDDField;
        
        private bool packPriceRefDDDFieldSpecified;
        
        private string prescriptionRestrictionsField;
        
        private string averageTreatmentPeriodField;
        
        private string concomitantTreatmentSpecificsField;
        
        private string treatmentSpecificsField;
        
        private MedicinalProductPDLRegisterDataTypeICDCodes iCDCodesField;
        
        /// <summary>
        /// MedicinalProductPDLRegisterDataType class constructor
        /// </summary>
        public MedicinalProductPDLRegisterDataType() {
            this.iCDCodesField = new MedicinalProductPDLRegisterDataTypeICDCodes();
            this.aTCCodesField = new ATCCodesType();
        }
        
        /// <summary>
        /// Наименование на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Наименование на регистър")]
        public string RegisterName {
            get {
                return this.registerNameField;
            }
            set {
                this.registerNameField = value;
            }
        }
        
        /// <summary>
        /// Дата на настъпили промени в обстоятелствата
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Дата на настъпили промени в обстоятелствата")]
        public System.DateTime PublishedAt {
            get {
                return this.publishedAtField;
            }
            set {
                this.publishedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishedAtSpecified {
            get {
                return this.publishedAtFieldSpecified;
            }
            set {
                this.publishedAtFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Уникален код на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Уникален код на регистър")]
        public string RegisterCode {
            get {
                return this.registerCodeField;
            }
            set {
                this.registerCodeField = value;
            }
        }
        
        /// <summary>
        /// Група ЛП
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Група ЛП")]
        public string Group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <summary>
        /// Анатомо-терапевтични кодове /ATC-кодове/
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Анатомо-терапевтични кодове /ATC-кодове/")]
        public ATCCodesType ATCCodes {
            get {
                return this.aTCCodesField;
            }
            set {
                this.aTCCodesField = value;
            }
        }
        
        /// <summary>
        /// Ниво на заплащане в %
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Ниво на заплащане в %")]
        public decimal ReimbursementPercent {
            get {
                return this.reimbursementPercentField;
            }
            set {
                this.reimbursementPercentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReimbursementPercentSpecified {
            get {
                return this.reimbursementPercentFieldSpecified;
            }
            set {
                this.reimbursementPercentFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Ниво на заплащане, стойност
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Ниво на заплащане, стойност")]
        public decimal ReimbursementValue {
            get {
                return this.reimbursementValueField;
            }
            set {
                this.reimbursementValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReimbursementValueSpecified {
            get {
                return this.reimbursementValueFieldSpecified;
            }
            set {
                this.reimbursementValueFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Препоръчителна дневна доза /DDD/ /терапевтичен курс
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Препоръчителна дневна доза /DDD/ /терапевтичен курс")]
        public string DDDValue {
            get {
                return this.dDDValueField;
            }
            set {
                this.dDDValueField = value;
            }
        }
        
        /// <summary>
        /// Мерна единица
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Мерна единица")]
        public string DDDUnit {
            get {
                return this.dDDUnitField;
            }
            set {
                this.dDDUnitField = value;
            }
        }
        
        /// <summary>
        /// Референтна стойност за DDD/ Терапевтичен курс
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DescriptionAttribute("Референтна стойност за DDD/ Терапевтичен курс")]
        public decimal DDDReferentValue {
            get {
                return this.dDDReferentValueField;
            }
            set {
                this.dDDReferentValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DDDReferentValueSpecified {
            get {
                return this.dDDReferentValueFieldSpecified;
            }
            set {
                this.dDDReferentValueFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Брой дневни дози в опаковка
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DescriptionAttribute("Брой дневни дози в опаковка")]
        public float PackDDDNumber {
            get {
                return this.packDDDNumberField;
            }
            set {
                this.packDDDNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackDDDNumberSpecified {
            get {
                return this.packDDDNumberFieldSpecified;
            }
            set {
                this.packDDDNumberFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Дали Референтна стойност за DDD/ Терапевтичен курс e по СЗО/WHO
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Дали Референтна стойност за DDD/ Терапевтичен курс e по СЗО/WHO")]
        public bool IsDddWHO {
            get {
                return this.isDddWHOField;
            }
            set {
                this.isDddWHOField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDddWHOSpecified {
            get {
                return this.isDddWHOFieldSpecified;
            }
            set {
                this.isDddWHOFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Стойност за опаковка, изчислена на база референтна стойност
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DescriptionAttribute("Стойност за опаковка, изчислена на база референтна стойност")]
        public decimal PackPriceRefDDD {
            get {
                return this.packPriceRefDDDField;
            }
            set {
                this.packPriceRefDDDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackPriceRefDDDSpecified {
            get {
                return this.packPriceRefDDDFieldSpecified;
            }
            set {
                this.packPriceRefDDDFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Терапевтични показания / Ограничение в начина на предписване при различни индикации
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DescriptionAttribute("Терапевтични показания / Ограничение в начина на предписване при различни индикац" +
            "ии")]
        public string PrescriptionRestrictions {
            get {
                return this.prescriptionRestrictionsField;
            }
            set {
                this.prescriptionRestrictionsField = value;
            }
        }
        
        /// <summary>
        /// Средна продължителност на лечението
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DescriptionAttribute("Средна продължителност на лечението")]
        public string AverageTreatmentPeriod {
            get {
                return this.averageTreatmentPeriodField;
            }
            set {
                this.averageTreatmentPeriodField = value;
            }
        }
        
        /// <summary>
        /// Особеност на дозировката и средна продължителност на лечението
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DescriptionAttribute("Особеност на дозировката и средна продължителност на лечението")]
        public string ConcomitantTreatmentSpecifics {
            get {
                return this.concomitantTreatmentSpecificsField;
            }
            set {
                this.concomitantTreatmentSpecificsField = value;
            }
        }
        
        /// <summary>
        /// Необходимост от съпровождащо лечение
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DescriptionAttribute("Необходимост от съпровождащо лечение")]
        public string TreatmentSpecifics {
            get {
                return this.treatmentSpecificsField;
            }
            set {
                this.treatmentSpecificsField = value;
            }
        }
        
        /// <summary>
        /// МКБ кодове
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        [System.ComponentModel.DescriptionAttribute("МКБ кодове")]
        public MedicinalProductPDLRegisterDataTypeICDCodes ICDCodes {
            get {
                return this.iCDCodesField;
            }
            set {
                this.iCDCodesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/NCPR/Common")]
    public partial class MedicinalProductPDLRegisterDataTypeICDCodes {
        
        private List<string> iCDCodeField;
        
        /// <summary>
        /// MedicinalProductPDLRegisterDataTypeICDCodes class constructor
        /// </summary>
        public MedicinalProductPDLRegisterDataTypeICDCodes() {
            this.iCDCodeField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ICDCode", Order=0)]
        public List<string> ICDCode {
            get {
                return this.iCDCodeField;
            }
            set {
                this.iCDCodeField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductPDLRegistersDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class medicinalProductPDLRegisterData : baseMedicinalProductRegisterData {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(medicinalProductCeilingPricesRegisterData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductCeilingPricesRegisterDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductCeilingPricesRegistersDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(medicinalProductMaxPricesRegisterData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductMaxPricesRegisterDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductMaxPricesRegistersDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(medicinalProductPDLRegisterData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductPDLRegistersDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public abstract partial class baseMedicinalProductRegisterData {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductCeilingPricesRegisterDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductCeilingPricesRegistersDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class medicinalProductCeilingPricesRegisterData : baseMedicinalProductRegisterData {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductCeilingPricesRegistersDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductCeilingPricesRegisterDataType : medicinalProductCeilingPricesRegisterData {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductCeilingPricesRegistersDataType : MedicinalProductCeilingPricesRegisterDataType {
        
        private List<MedicinalProductCeilingPriceRegisterDataType> medicinalProductCeilingPriceRegisterDataField;
        
        /// <summary>
        /// MedicinalProductCeilingPricesRegistersDataType class constructor
        /// </summary>
        public MedicinalProductCeilingPricesRegistersDataType() {
            this.medicinalProductCeilingPriceRegisterDataField = new List<MedicinalProductCeilingPriceRegisterDataType>();
        }
        
        /// <summary>
        /// Данни за лекарствен продукт в Регистър на пределните цени
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MedicinalProductCeilingPriceRegisterData", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Данни за лекарствен продукт в Регистър на пределните цени")]
        public List<MedicinalProductCeilingPriceRegisterDataType> MedicinalProductCeilingPriceRegisterData {
            get {
                return this.medicinalProductCeilingPriceRegisterDataField;
            }
            set {
                this.medicinalProductCeilingPriceRegisterDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductCeilingPriceRegisterDataType {
        
        private System.DateTime publishedAtField;
        
        private bool publishedAtFieldSpecified;
        
        private string registerNameField;
        
        private string registerCodeField;
        
        /// <summary>
        /// Дата на настъпили промени в обстоятелствата
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Дата на настъпили промени в обстоятелствата")]
        public System.DateTime PublishedAt {
            get {
                return this.publishedAtField;
            }
            set {
                this.publishedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishedAtSpecified {
            get {
                return this.publishedAtFieldSpecified;
            }
            set {
                this.publishedAtFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Наименование на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Наименование на регистър")]
        public string RegisterName {
            get {
                return this.registerNameField;
            }
            set {
                this.registerNameField = value;
            }
        }
        
        /// <summary>
        /// Уникален код на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Уникален код на регистър")]
        public string RegisterCode {
            get {
                return this.registerCodeField;
            }
            set {
                this.registerCodeField = value;
            }
        }
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductMaxPricesRegisterDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductMaxPricesRegistersDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class medicinalProductMaxPricesRegisterData : baseMedicinalProductRegisterData {
    }
    
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MedicinalProductMaxPricesRegistersDataType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductMaxPricesRegisterDataType : medicinalProductMaxPricesRegisterData {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductMaxPricesRegistersDataType : MedicinalProductMaxPricesRegisterDataType {
        
        private List<MedicinalProductMaxPriceRegisterDataType> medicinalProductMaxPriceRegisterDataField;
        
        /// <summary>
        /// MedicinalProductMaxPricesRegistersDataType class constructor
        /// </summary>
        public MedicinalProductMaxPricesRegistersDataType() {
            this.medicinalProductMaxPriceRegisterDataField = new List<MedicinalProductMaxPriceRegisterDataType>();
        }
        
        /// <summary>
        /// Данни за лекарствен продукт в Регистър на максималните продажни цени
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("MedicinalProductMaxPriceRegisterData", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Данни за лекарствен продукт в Регистър на максималните продажни цени")]
        public List<MedicinalProductMaxPriceRegisterDataType> MedicinalProductMaxPriceRegisterData {
            get {
                return this.medicinalProductMaxPriceRegisterDataField;
            }
            set {
                this.medicinalProductMaxPriceRegisterDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29155")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NCPR/Common", IsNullable=true)]
    public partial class MedicinalProductMaxPriceRegisterDataType {
        
        private System.DateTime publishedAtField;
        
        private bool publishedAtFieldSpecified;
        
        private string registerNameField;
        
        private string registerCodeField;
        
        private decimal maximumPriceField;
        
        private bool maximumPriceFieldSpecified;
        
        /// <summary>
        /// Дата на настъпили промени в обстоятелствата
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Дата на настъпили промени в обстоятелствата")]
        public System.DateTime PublishedAt {
            get {
                return this.publishedAtField;
            }
            set {
                this.publishedAtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PublishedAtSpecified {
            get {
                return this.publishedAtFieldSpecified;
            }
            set {
                this.publishedAtFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Наименование на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Наименование на регистър")]
        public string RegisterName {
            get {
                return this.registerNameField;
            }
            set {
                this.registerNameField = value;
            }
        }
        
        /// <summary>
        /// Уникален код на регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Уникален код на регистър")]
        public string RegisterCode {
            get {
                return this.registerCodeField;
            }
            set {
                this.registerCodeField = value;
            }
        }
        
        /// <summary>
        /// Максимална цена
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Максимална цена")]
        public decimal MaximumPrice {
            get {
                return this.maximumPriceField;
            }
            set {
                this.maximumPriceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaximumPriceSpecified {
            get {
                return this.maximumPriceFieldSpecified;
            }
            set {
                this.maximumPriceFieldSpecified = value;
            }
        }
    }
}
