// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.20336
//    <NameSpace>TechnoLogica.RegiX.NRAPublicDebtsCollectionAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.NRAPublicDebtsCollectionAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18834")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NRA/PublicDebtsCollection/SendDataForNewIOAndCollectionReque" +
        "st")]
    [System.Xml.Serialization.XmlRootAttribute("SendDataForNewIOAndCollectionRequest", Namespace="http://egov.bg/RegiX/NRA/PublicDebtsCollection/SendDataForNewIOAndCollectionReque" +
        "st", IsNullable=false)]
    public partial class SendDataForNewIOAndCollectionRequestType {
        
        private NewIOAndCollectionType ioField;
        
        private List<CollectionType> collectionsField;
        
        /// <summary>
        /// SendDataForNewIOAndCollectionRequestType class constructor
        /// </summary>
        public SendDataForNewIOAndCollectionRequestType() {
            this.collectionsField = new List<CollectionType>();
            this.ioField = new NewIOAndCollectionType();
        }
        
        /// <summary>
        /// Изпълнително основание (ИО)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Изпълнително основание (ИО)")]
        public NewIOAndCollectionType IO {
            get {
                return this.ioField;
            }
            set {
                this.ioField = value;
            }
        }
        
        /// <summary>
        /// Вземане
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Collection", IsNullable=false)]
        [System.ComponentModel.DescriptionAttribute("Вземане")]
        public List<CollectionType> Collections {
            get {
                return this.collectionsField;
            }
            set {
                this.collectionsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18834")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NRA/PublicDebtsCollection/SendDataForNewIOAndCollectionReque" +
        "st")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NRA/PublicDebtsCollection/SendDataForNewIOAndCollectionReque" +
        "st", IsNullable=true)]
    public partial class NewIOAndCollectionType {
        
        private long actIssurerIDField;
        
        private long subdivisionIDField;
        
        private string subdivisionEIKField;
        
        private long titulIDField;
        
        private string eIKField;
        
        private EIKTypeEnumeration eIKTypeField;
        
        private string documentTypeField;
        
        private string documentNoField;
        
        private string documentSeriesField;
        
        private System.DateTime issueDateField;
        
        private System.DateTime enforcementDateField;
        
        private bool enforcementDateFieldSpecified;
        
        private bool enforceInAdvanceField;
        
        private string deedTypeField;
        
        private string deedIDField;
        
        private uint deedYearField;
        
        private bool deedYearFieldSpecified;
        
        /// <summary>
        /// ID на взискател/актосъставител
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("ID на взискател/актосъставител")]
        public long ActIssurerID {
            get {
                return this.actIssurerIDField;
            }
            set {
                this.actIssurerIDField = value;
            }
        }
        
        /// <summary>
        /// ID на подразделение
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("ID на подразделение")]
        public long SubdivisionID {
            get {
                return this.subdivisionIDField;
            }
            set {
                this.subdivisionIDField = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на взискател/актосъставител
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на взискател/актосъставител")]
        public string SubdivisionEIK {
            get {
                return this.subdivisionEIKField;
            }
            set {
                this.subdivisionEIKField = value;
            }
        }
        
        /// <summary>
        /// ID на ИО
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("ID на ИО")]
        public long TitulID {
            get {
                return this.titulIDField;
            }
            set {
                this.titulIDField = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на длъжник
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на длъжник")]
        public string EIK {
            get {
                return this.eIKField;
            }
            set {
                this.eIKField = value;
            }
        }
        
        /// <summary>
        /// Тип идентификатор на длъжник
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Тип идентификатор на длъжник")]
        public EIKTypeEnumeration EIKType {
            get {
                return this.eIKTypeField;
            }
            set {
                this.eIKTypeField = value;
            }
        }
        
        /// <summary>
        /// Вид на документа – изпълнително основание
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Вид на документа – изпълнително основание")]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <summary>
        /// Номер на документ – изпълнително основание
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Номер на документ – изпълнително основание")]
        public string DocumentNo {
            get {
                return this.documentNoField;
            }
            set {
                this.documentNoField = value;
            }
        }
        
        /// <summary>
        /// Серия на документ – изпълнително основание
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Серия на документ – изпълнително основание")]
        public string DocumentSeries {
            get {
                return this.documentSeriesField;
            }
            set {
                this.documentSeriesField = value;
            }
        }
        
        /// <summary>
        /// Дата на издаване на документ – изпълнително основание
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        [System.ComponentModel.DescriptionAttribute("Дата на издаване на документ – изпълнително основание")]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
            }
        }
        
        /// <summary>
        /// Дата на влизане в сила на документа – изпълнително основание
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        [System.ComponentModel.DescriptionAttribute("Дата на влизане в сила на документа – изпълнително основание")]
        public System.DateTime EnforcementDate {
            get {
                return this.enforcementDateField;
            }
            set {
                this.enforcementDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EnforcementDateSpecified {
            get {
                return this.enforcementDateFieldSpecified;
            }
            set {
                this.enforcementDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Акт подлежащ на предварително изпълнение
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Акт подлежащ на предварително изпълнение")]
        public bool EnforceInAdvance {
            get {
                return this.enforceInAdvanceField;
            }
            set {
                this.enforceInAdvanceField = value;
            }
        }
        
        /// <summary>
        /// Вид дело от номенклатура
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DescriptionAttribute("Вид дело от номенклатура")]
        public string DeedType {
            get {
                return this.deedTypeField;
            }
            set {
                this.deedTypeField = value;
            }
        }
        
        /// <summary>
        /// Номер на дело
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DescriptionAttribute("Номер на дело")]
        public string DeedID {
            get {
                return this.deedIDField;
            }
            set {
                this.deedIDField = value;
            }
        }
        
        /// <summary>
        /// Година на дело
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DescriptionAttribute("Година на дело")]
        public uint DeedYear {
            get {
                return this.deedYearField;
            }
            set {
                this.deedYearField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeedYearSpecified {
            get {
                return this.deedYearFieldSpecified;
            }
            set {
                this.deedYearFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18834")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/NRA/PublicDebtsCollection/SendDataForNewIOAndCollectionReque" +
        "st")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/NRA/PublicDebtsCollection/SendDataForNewIOAndCollectionReque" +
        "st", IsNullable=true)]
    public partial class CollectionsNewIOType {
        
        private List<CollectionType> collectionField;
        
        /// <summary>
        /// CollectionsNewIOType class constructor
        /// </summary>
        public CollectionsNewIOType() {
            this.collectionField = new List<CollectionType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Collection", Order=0)]
        public List<CollectionType> Collection {
            get {
                return this.collectionField;
            }
            set {
                this.collectionField = value;
            }
        }
    }
}
