// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.19886
//    <NameSpace>TechnoLogica.RegiX.REZMAAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.REZMAAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29952")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AM/REZMA/CustomsObligationsResponse")]
    [System.Xml.Serialization.XmlRootAttribute("CustomsObligationsResponse", Namespace="http://egov.bg/RegiX/AM/REZMA/CustomsObligationsResponse", IsNullable=false)]
    public partial class CustomsObligationsResponseType {
        
        private string uINField;
        
        private string nameField;
        
        private List<ObligationType> obligationsField;
        
        /// <summary>
        /// CustomsObligationsResponseType class constructor
        /// </summary>
        public CustomsObligationsResponseType() {
            this.obligationsField = new List<ObligationType>();
        }
        
        /// <summary>
        /// Идентификатор: Булстат, ЕГН, ЕИК или ЛНЧ
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор: Булстат, ЕГН, ЕИК или ЛНЧ")]
        public string UIN {
            get {
                return this.uINField;
            }
            set {
                this.uINField = value;
            }
        }
        
        /// <summary>
        /// Име - на физическо или юридическо лице
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Име - на физическо или юридическо лице")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <summary>
        /// Задължения
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Obligation", Namespace="http://egov.bg/RegiX/AM/REZMA", IsNullable=false)]
        [System.ComponentModel.DescriptionAttribute("Задължения")]
        public List<ObligationType> Obligations {
            get {
                return this.obligationsField;
            }
            set {
                this.obligationsField = value;
            }
        }
    }
}
