// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.24420
//    <NameSpace>TechnoLogica.RegiX.ASPFosterParentsAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.ASPFosterParentsAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18350")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest", IsNullable=false)]
    public partial class AspFosterParentsRequest {
        
        private AspHeader headerField;
        
        private AspData dataField;
        
        /// <summary>
        /// AspFosterParentsRequest class constructor
        /// </summary>
        public AspFosterParentsRequest() {
            this.dataField = new AspData();
            this.headerField = new AspHeader();
        }
        
        /// <summary>
        /// Заглавна част на запитването
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Заглавна част на запитването")]
        public AspHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <summary>
        /// Детайли на запитването
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Детайли на запитването")]
        public AspData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18350")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest", IsNullable=true)]
    public partial class AspHeader {
        
        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private int requestSizeField;
        
        private string isunCodeField;
        
        /// <summary>
        /// Начална дата (включително)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Начална дата (включително)")]
        public System.DateTime StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <summary>
        /// Крайна дата (включително)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        [System.ComponentModel.DescriptionAttribute("Крайна дата (включително)")]
        public System.DateTime EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <summary>
        /// Брой редове в запитването
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Брой редове в запитването")]
        public int RequestSize {
            get {
                return this.requestSizeField;
            }
            set {
                this.requestSizeField = value;
            }
        }
        
        /// <summary>
        /// Kод на проекта, за който се иска информация за договор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Kод на проекта, за който се иска информация за договор")]
        public string IsunCode {
            get {
                return this.isunCodeField;
            }
            set {
                this.isunCodeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18350")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest", IsNullable=true)]
    public partial class AspDataItem {
        
        private int rowField;
        
        private IdentTypeType identTypeParentField;
        
        private bool identTypeParentFieldSpecified;
        
        private string identificatorParentField;
        
        private IdentTypeType identTypeChildField;
        
        private bool identTypeChildFieldSpecified;
        
        private string identificatorChildField;
        
        /// <summary>
        /// Номер на ред
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Номер на ред")]
        public int Row {
            get {
                return this.rowField;
            }
            set {
                this.rowField = value;
            }
        }
        
        /// <summary>
        /// Тип на идентификатора на лице "Приемен родител" (1- ЕГН, 2 - ЛНЧ)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Тип на идентификатора на лице \"Приемен родител\" (1- ЕГН, 2 - ЛНЧ)")]
        public IdentTypeType IdentTypeParent {
            get {
                return this.identTypeParentField;
            }
            set {
                this.identTypeParentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentTypeParentSpecified {
            get {
                return this.identTypeParentFieldSpecified;
            }
            set {
                this.identTypeParentFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на лице "Приемен родител"
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на лице \"Приемен родител\"")]
        public string IdentificatorParent {
            get {
                return this.identificatorParentField;
            }
            set {
                this.identificatorParentField = value;
            }
        }
        
        /// <summary>
        /// Тип на идентификатора на лице "Настанено дете" (1- ЕГН, 2 - ЛНЧ)
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Тип на идентификатора на лице \"Настанено дете\" (1- ЕГН, 2 - ЛНЧ)")]
        public IdentTypeType IdentTypeChild {
            get {
                return this.identTypeChildField;
            }
            set {
                this.identTypeChildField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdentTypeChildSpecified {
            get {
                return this.identTypeChildFieldSpecified;
            }
            set {
                this.identTypeChildFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на лице "Настанено дете"
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на лице \"Настанено дете\"")]
        public string IdentificatorChild {
            get {
                return this.identificatorChildField;
            }
            set {
                this.identificatorChildField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18350")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest")]
    public enum IdentTypeType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.18350")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/ASP/SendRequestForFosterParents/AspFosterParentsRequest", IsNullable=true)]
    public partial class AspData {
        
        private List<AspDataItem> dataItemField;
        
        /// <summary>
        /// AspData class constructor
        /// </summary>
        public AspData() {
            this.dataItemField = new List<AspDataItem>();
        }
        
        /// <summary>
        /// Данни за дете/приемен родител
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("DataItem", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Данни за дете/приемен родител")]
        public List<AspDataItem> DataItem {
            get {
                return this.dataItemField;
            }
            set {
                this.dataItemField = value;
            }
        }
    }
}
