// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.29597
//    <NameSpace>TechnoLogica.RegiX.AVTRAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.AVTRAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute("TestStatusType", Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=false)]
    public enum StatusType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Нова партида")]
        Новапартида,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Пререгистрирана партида")]
        Пререгистриранапартида,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Нова закрита партида")]
        Новазакритапартида,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Пререгистрирана закрита партида")]
        Пререгистрираназакритапартида,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class Persons {
        
        private List<SubjectType> personField;
        
        /// <summary>
        /// Persons class constructor
        /// </summary>
        public Persons() {
            this.personField = new List<SubjectType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Person", Order=0)]
        public List<SubjectType> Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class SubjectType {
        
        private string indentField;
        
        private string nameField;
        
        private IndentTypeType indentTypeField;
        
        private bool indentTypeFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Indent {
            get {
                return this.indentField;
            }
            set {
                this.indentField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public IndentTypeType IndentType {
            get {
                return this.indentTypeField;
            }
            set {
                this.indentTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IndentTypeSpecified {
            get {
                return this.indentTypeFieldSpecified;
            }
            set {
                this.indentTypeFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    public enum IndentTypeType {
        
        /// <remarks/>
        EGN,
        
        /// <remarks/>
        UIC,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class PersonInformationType {
        
        private string nameField;
        
        private string surnameField;
        
        private string familyField;
        
        private object eGNField;
        
        /// <summary>
        /// Име
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Име")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <summary>
        /// Презиме
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Презиме")]
        public string Surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
            }
        }
        
        /// <summary>
        /// Фамилия
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Фамилия")]
        public string Family {
            get {
                return this.familyField;
            }
            set {
                this.familyField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object EGN {
            get {
                return this.eGNField;
            }
            set {
                this.eGNField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class CompanyParticipationType {
        
        private List<CompanyParticipationTypeCompany> companyField;
        
        /// <summary>
        /// CompanyParticipationType class constructor
        /// </summary>
        public CompanyParticipationType() {
            this.companyField = new List<CompanyParticipationTypeCompany>();
        }
        
        /// <summary>
        /// Търговско дружество
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Company", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Търговско дружество")]
        public List<CompanyParticipationTypeCompany> Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/AV/TR")]
    public partial class CompanyParticipationTypeCompany {
        
        private string eIKField;
        
        private string companyNameField;
        
        private LegalFormType legalFormField;
        
        private List<string> fieldsField;
        
        /// <summary>
        /// CompanyParticipationTypeCompany class constructor
        /// </summary>
        public CompanyParticipationTypeCompany() {
            this.fieldsField = new List<string>();
            this.legalFormField = new LegalFormType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EIK {
            get {
                return this.eIKField;
            }
            set {
                this.eIKField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public LegalFormType LegalForm {
            get {
                return this.legalFormField;
            }
            set {
                this.legalFormField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false)]
        public List<string> Fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class LegalFormType {
        
        private string legalFormAbbrField;
        
        private string legalFormNameField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string LegalFormAbbr {
            get {
                return this.legalFormAbbrField;
            }
            set {
                this.legalFormAbbrField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string LegalFormName {
            get {
                return this.legalFormNameField;
            }
            set {
                this.legalFormNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class FieldsType {
        
        private List<string> fieldField;
        
        /// <summary>
        /// FieldsType class constructor
        /// </summary>
        public FieldsType() {
            this.fieldField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Field", Order=0)]
        public List<string> Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class SeatType {
        
        private AddressType addressField;
        
        private ContactsType contactsField;
        
        /// <summary>
        /// SeatType class constructor
        /// </summary>
        public SeatType() {
            this.contactsField = new ContactsType();
            this.addressField = new AddressType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContactsType Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class AddressType {
        
        private string countryCodeField;
        
        private string countryField;
        
        private string isForeignField;
        
        private string districtEkatteField;
        
        private string districtField;
        
        private string municipalityEkatteField;
        
        private string municipalityField;
        
        private string settlementEKATTEField;
        
        private string settlementField;
        
        private string areaField;
        
        private string areaEkatteField;
        
        private string postCodeField;
        
        private string foreignPlaceField;
        
        private string housingEstateField;
        
        private string streetField;
        
        private string streetNumberField;
        
        private string blockField;
        
        private string entranceField;
        
        private string floorField;
        
        private string apartmentField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IsForeign {
            get {
                return this.isForeignField;
            }
            set {
                this.isForeignField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DistrictEkatte {
            get {
                return this.districtEkatteField;
            }
            set {
                this.districtEkatteField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string District {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MunicipalityEkatte {
            get {
                return this.municipalityEkatteField;
            }
            set {
                this.municipalityEkatteField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Municipality {
            get {
                return this.municipalityField;
            }
            set {
                this.municipalityField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SettlementEKATTE {
            get {
                return this.settlementEKATTEField;
            }
            set {
                this.settlementEKATTEField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Settlement {
            get {
                return this.settlementField;
            }
            set {
                this.settlementField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string AreaEkatte {
            get {
                return this.areaEkatteField;
            }
            set {
                this.areaEkatteField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ForeignPlace {
            get {
                return this.foreignPlaceField;
            }
            set {
                this.foreignPlaceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string HousingEstate {
            get {
                return this.housingEstateField;
            }
            set {
                this.housingEstateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string Entrance {
            get {
                return this.entranceField;
            }
            set {
                this.entranceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class ContactsType {
        
        private string phoneField;
        
        private string faxField;
        
        private string eMailField;
        
        private string uRLField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string EMail {
            get {
                return this.eMailField;
            }
            set {
                this.eMailField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class SubjectOfActivityType {
        
        private string subjectField;
        
        private bool isBankField;
        
        private bool isBankFieldSpecified;
        
        private bool isInsurerField;
        
        private bool isInsurerFieldSpecified;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsBank {
            get {
                return this.isBankField;
            }
            set {
                this.isBankField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBankSpecified {
            get {
                return this.isBankFieldSpecified;
            }
            set {
                this.isBankFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsInsurer {
            get {
                return this.isInsurerField;
            }
            set {
                this.isInsurerField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsInsurerSpecified {
            get {
                return this.isInsurerFieldSpecified;
            }
            set {
                this.isInsurerFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class NKIDType {
        
        private string nKIDcodeField;
        
        private string nKIDnameField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NKIDcode {
            get {
                return this.nKIDcodeField;
            }
            set {
                this.nKIDcodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NKIDname {
            get {
                return this.nKIDnameField;
            }
            set {
                this.nKIDnameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class MandateType {
        
        private string typeField;
        
        private string mandateValueField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MandateValue {
            get {
                return this.mandateValueField;
            }
            set {
                this.mandateValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class SharesType {
        
        private List<ShareType> shareField;
        
        /// <summary>
        /// SharesType class constructor
        /// </summary>
        public SharesType() {
            this.shareField = new List<ShareType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Share", Order=0)]
        public List<ShareType> Share {
            get {
                return this.shareField;
            }
            set {
                this.shareField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class ShareType {
        
        private string typeField;
        
        private string countField;
        
        private string nominalValueField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NominalValue {
            get {
                return this.nominalValueField;
            }
            set {
                this.nominalValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class CapitalAmountType {
        
        private string valueField;
        
        private string euroField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Euro {
            get {
                return this.euroField;
            }
            set {
                this.euroField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class NonMonetaryDepositsType {
        
        private List<NonMonetaryDepositType> nonMonetaryDepositField;
        
        /// <summary>
        /// NonMonetaryDepositsType class constructor
        /// </summary>
        public NonMonetaryDepositsType() {
            this.nonMonetaryDepositField = new List<NonMonetaryDepositType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("NonMonetaryDeposit", Order=0)]
        public List<NonMonetaryDepositType> NonMonetaryDeposit {
            get {
                return this.nonMonetaryDepositField;
            }
            set {
                this.nonMonetaryDepositField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class NonMonetaryDepositType {
        
        private string descriptionField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class DetailsType {
        
        private List<DetailType> detailField;
        
        /// <summary>
        /// DetailsType class constructor
        /// </summary>
        public DetailsType() {
            this.detailField = new List<DetailType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Detail", Order=0)]
        public List<DetailType> Detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class DetailType {
        
        private string fieldNameField;
        
        private string fieldCodeField;
        
        private string fieldOrderField;
        
        private SubjectType subjectField;
        
        /// <summary>
        /// DetailType class constructor
        /// </summary>
        public DetailType() {
            this.subjectField = new SubjectType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FieldName {
            get {
                return this.fieldNameField;
            }
            set {
                this.fieldNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FieldCode {
            get {
                return this.fieldCodeField;
            }
            set {
                this.fieldCodeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FieldOrder {
            get {
                return this.fieldOrderField;
            }
            set {
                this.fieldOrderField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SubjectType Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.33226")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/TR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/TR", IsNullable=true)]
    public partial class AddemptionOfTraderType {
        
        private AddressType addressField;
        
        private ContactsType contactsField;
        
        private string competentAuthorityForRegistrationField;
        
        private string registrationNumberField;
        
        /// <summary>
        /// AddemptionOfTraderType class constructor
        /// </summary>
        public AddemptionOfTraderType() {
            this.contactsField = new ContactsType();
            this.addressField = new AddressType();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ContactsType Contacts {
            get {
                return this.contactsField;
            }
            set {
                this.contactsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CompetentAuthorityForRegistration {
            get {
                return this.competentAuthorityForRegistrationField;
            }
            set {
                this.competentAuthorityForRegistrationField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RegistrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
            }
        }
    }
}
