//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GovReportShip", Namespace="http://marad.bg/")]
    [System.SerializableAttribute()]
    public partial class GovReportShip : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipRegistration RegistrationInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipOwner[] OwnersInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipCharacteristics CharacteristicsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipRegistration RegistrationInfo {
            get {
                return this.RegistrationInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationInfoField, value) != true)) {
                    this.RegistrationInfoField = value;
                    this.RaisePropertyChanged("RegistrationInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipOwner[] OwnersInfo {
            get {
                return this.OwnersInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnersInfoField, value) != true)) {
                    this.OwnersInfoField = value;
                    this.RaisePropertyChanged("OwnersInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipCharacteristics Characteristics {
            get {
                return this.CharacteristicsField;
            }
            set {
                if ((object.ReferenceEquals(this.CharacteristicsField, value) != true)) {
                    this.CharacteristicsField = value;
                    this.RaisePropertyChanged("Characteristics");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipRegistration", Namespace="http://marad.bg/")]
    [System.SerializableAttribute()]
    public partial class ShipRegistration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipNameLatinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegistrationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TomField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        private TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.StatusEnum StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShipName {
            get {
                return this.ShipNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipNameField, value) != true)) {
                    this.ShipNameField = value;
                    this.RaisePropertyChanged("ShipName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ShipNameLatin {
            get {
                return this.ShipNameLatinField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipNameLatinField, value) != true)) {
                    this.ShipNameLatinField = value;
                    this.RaisePropertyChanged("ShipNameLatin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RegistrationPort {
            get {
                return this.RegistrationPortField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationPortField, value) != true)) {
                    this.RegistrationPortField = value;
                    this.RaisePropertyChanged("RegistrationPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string RegistrationNumber {
            get {
                return this.RegistrationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RegistrationNumberField, value) != true)) {
                    this.RegistrationNumberField = value;
                    this.RaisePropertyChanged("RegistrationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Tom {
            get {
                return this.TomField;
            }
            set {
                if ((object.ReferenceEquals(this.TomField, value) != true)) {
                    this.TomField = value;
                    this.RaisePropertyChanged("Tom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Page {
            get {
                return this.PageField;
            }
            set {
                if ((object.ReferenceEquals(this.PageField, value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.StatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipCharacteristics", Namespace="http://marad.bg/")]
    [System.SerializableAttribute()]
    public partial class ShipCharacteristics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<decimal> BTField;
        
        private System.Nullable<decimal> NTField;
        
        private System.Nullable<decimal> MaxLengthField;
        
        private System.Nullable<decimal> MaxWidthField;
        
        private System.Nullable<decimal> WaterplaneField;
        
        private System.Nullable<decimal> DisplacementField;
        
        private System.Nullable<decimal> ShipboardHeightField;
        
        private System.Nullable<decimal> DWField;
        
        private System.Nullable<int> NumberOfEnginesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnginesFuelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Engine[] EnginesField;
        
        private double SumEnginePowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BodyNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> BT {
            get {
                return this.BTField;
            }
            set {
                if ((this.BTField.Equals(value) != true)) {
                    this.BTField = value;
                    this.RaisePropertyChanged("BT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> NT {
            get {
                return this.NTField;
            }
            set {
                if ((this.NTField.Equals(value) != true)) {
                    this.NTField = value;
                    this.RaisePropertyChanged("NT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> MaxLength {
            get {
                return this.MaxLengthField;
            }
            set {
                if ((this.MaxLengthField.Equals(value) != true)) {
                    this.MaxLengthField = value;
                    this.RaisePropertyChanged("MaxLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> MaxWidth {
            get {
                return this.MaxWidthField;
            }
            set {
                if ((this.MaxWidthField.Equals(value) != true)) {
                    this.MaxWidthField = value;
                    this.RaisePropertyChanged("MaxWidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> Waterplane {
            get {
                return this.WaterplaneField;
            }
            set {
                if ((this.WaterplaneField.Equals(value) != true)) {
                    this.WaterplaneField = value;
                    this.RaisePropertyChanged("Waterplane");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<decimal> Displacement {
            get {
                return this.DisplacementField;
            }
            set {
                if ((this.DisplacementField.Equals(value) != true)) {
                    this.DisplacementField = value;
                    this.RaisePropertyChanged("Displacement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> ShipboardHeight {
            get {
                return this.ShipboardHeightField;
            }
            set {
                if ((this.ShipboardHeightField.Equals(value) != true)) {
                    this.ShipboardHeightField = value;
                    this.RaisePropertyChanged("ShipboardHeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> DW {
            get {
                return this.DWField;
            }
            set {
                if ((this.DWField.Equals(value) != true)) {
                    this.DWField = value;
                    this.RaisePropertyChanged("DW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> NumberOfEngines {
            get {
                return this.NumberOfEnginesField;
            }
            set {
                if ((this.NumberOfEnginesField.Equals(value) != true)) {
                    this.NumberOfEnginesField = value;
                    this.RaisePropertyChanged("NumberOfEngines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string EnginesFuel {
            get {
                return this.EnginesFuelField;
            }
            set {
                if ((object.ReferenceEquals(this.EnginesFuelField, value) != true)) {
                    this.EnginesFuelField = value;
                    this.RaisePropertyChanged("EnginesFuel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Engine[] Engines {
            get {
                return this.EnginesField;
            }
            set {
                if ((object.ReferenceEquals(this.EnginesField, value) != true)) {
                    this.EnginesField = value;
                    this.RaisePropertyChanged("Engines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double SumEnginePower {
            get {
                return this.SumEnginePowerField;
            }
            set {
                if ((this.SumEnginePowerField.Equals(value) != true)) {
                    this.SumEnginePowerField = value;
                    this.RaisePropertyChanged("SumEnginePower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string BodyNumber {
            get {
                return this.BodyNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BodyNumberField, value) != true)) {
                    this.BodyNumberField = value;
                    this.RaisePropertyChanged("BodyNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShipOwner", Namespace="http://marad.bg/")]
    [System.SerializableAttribute()]
    public partial class ShipOwner : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<bool> FirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FamilyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BulstatEGNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImoNumberField;
        
        private System.Nullable<bool> IsUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<bool> Firm {
            get {
                return this.FirmField;
            }
            set {
                if ((this.FirmField.Equals(value) != true)) {
                    this.FirmField = value;
                    this.RaisePropertyChanged("Firm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SurName {
            get {
                return this.SurNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurNameField, value) != true)) {
                    this.SurNameField = value;
                    this.RaisePropertyChanged("SurName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FamilyName {
            get {
                return this.FamilyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyNameField, value) != true)) {
                    this.FamilyNameField = value;
                    this.RaisePropertyChanged("FamilyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BulstatEGN {
            get {
                return this.BulstatEGNField;
            }
            set {
                if ((object.ReferenceEquals(this.BulstatEGNField, value) != true)) {
                    this.BulstatEGNField = value;
                    this.RaisePropertyChanged("BulstatEGN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ImoNumber {
            get {
                return this.ImoNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ImoNumberField, value) != true)) {
                    this.ImoNumberField = value;
                    this.RaisePropertyChanged("ImoNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> IsUser {
            get {
                return this.IsUserField;
            }
            set {
                if ((this.IsUserField.Equals(value) != true)) {
                    this.IsUserField = value;
                    this.RaisePropertyChanged("IsUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusEnum", Namespace="http://marad.bg/")]
    public enum StatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Erased = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Engine", Namespace="http://marad.bg/")]
    [System.SerializableAttribute()]
    public partial class Engine : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SystemModificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngineNumberField;
        
        private System.Nullable<int> PowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnginteTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SystemModification {
            get {
                return this.SystemModificationField;
            }
            set {
                if ((object.ReferenceEquals(this.SystemModificationField, value) != true)) {
                    this.SystemModificationField = value;
                    this.RaisePropertyChanged("SystemModification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EngineNumber {
            get {
                return this.EngineNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EngineNumberField, value) != true)) {
                    this.EngineNumberField = value;
                    this.RaisePropertyChanged("EngineNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> Power {
            get {
                return this.PowerField;
            }
            set {
                if ((this.PowerField.Equals(value) != true)) {
                    this.PowerField = value;
                    this.RaisePropertyChanged("Power");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EnginteType {
            get {
                return this.EnginteTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EnginteTypeField, value) != true)) {
                    this.EnginteTypeField = value;
                    this.RaisePropertyChanged("EnginteType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nomenclature", Namespace="http://marad.bg/")]
    [System.SerializableAttribute()]
    public partial class Nomenclature : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://marad.bg/", ConfigurationName="VesselsReportService.GovServiceReportSoap")]
    public interface GovServiceReportSoap {
        
        // CODEGEN: Generating message contract since element name egn from namespace http://marad.bg/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marad.bg/ShipsByOwner", ReplyAction="*")]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerResponse ShipsByOwner(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name ShipTypeResult from namespace http://marad.bg/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marad.bg/ShipType", ReplyAction="*")]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeResponse ShipType(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeRequest request);
        
        // CODEGEN: Generating message contract since element name ShipSubTypeResult from namespace http://marad.bg/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marad.bg/ShipSubType", ReplyAction="*")]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeResponse ShipSubType(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeRequest request);
        
        // CODEGEN: Generating message contract since element name EngineFuelResult from namespace http://marad.bg/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marad.bg/EngineFuel", ReplyAction="*")]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelResponse EngineFuel(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelRequest request);
        
        // CODEGEN: Generating message contract since element name shipType from namespace http://marad.bg/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marad.bg/ShipByCharacteristicTest", ReplyAction="*")]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestResponse ShipByCharacteristicTest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestRequest request);
        
        // CODEGEN: Generating message contract since element name hullNumber from namespace http://marad.bg/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://marad.bg/ShipByCharacteristics", ReplyAction="*")]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsResponse ShipByCharacteristics(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipsByOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipsByOwner", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerRequestBody Body;
        
        public ShipsByOwnerRequest() {
        }
        
        public ShipsByOwnerRequest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipsByOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string egn;
        
        public ShipsByOwnerRequestBody() {
        }
        
        public ShipsByOwnerRequestBody(string egn) {
            this.egn = egn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipsByOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipsByOwnerResponse", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerResponseBody Body;
        
        public ShipsByOwnerResponse() {
        }
        
        public ShipsByOwnerResponse(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipsByOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipsByOwnerResult;
        
        public ShipsByOwnerResponseBody() {
        }
        
        public ShipsByOwnerResponseBody(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipsByOwnerResult) {
            this.ShipsByOwnerResult = ShipsByOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipType", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeRequestBody Body;
        
        public ShipTypeRequest() {
        }
        
        public ShipTypeRequest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShipTypeRequestBody {
        
        public ShipTypeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipTypeResponse", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeResponseBody Body;
        
        public ShipTypeResponse() {
        }
        
        public ShipTypeResponse(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] ShipTypeResult;
        
        public ShipTypeResponseBody() {
        }
        
        public ShipTypeResponseBody(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] ShipTypeResult) {
            this.ShipTypeResult = ShipTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipSubTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipSubType", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeRequestBody Body;
        
        public ShipSubTypeRequest() {
        }
        
        public ShipSubTypeRequest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ShipSubTypeRequestBody {
        
        public ShipSubTypeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipSubTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipSubTypeResponse", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeResponseBody Body;
        
        public ShipSubTypeResponse() {
        }
        
        public ShipSubTypeResponse(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipSubTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] ShipSubTypeResult;
        
        public ShipSubTypeResponseBody() {
        }
        
        public ShipSubTypeResponseBody(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] ShipSubTypeResult) {
            this.ShipSubTypeResult = ShipSubTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EngineFuelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EngineFuel", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelRequestBody Body;
        
        public EngineFuelRequest() {
        }
        
        public EngineFuelRequest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EngineFuelRequestBody {
        
        public EngineFuelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EngineFuelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EngineFuelResponse", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelResponseBody Body;
        
        public EngineFuelResponse() {
        }
        
        public EngineFuelResponse(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class EngineFuelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] EngineFuelResult;
        
        public EngineFuelResponseBody() {
        }
        
        public EngineFuelResponseBody(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] EngineFuelResult) {
            this.EngineFuelResult = EngineFuelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipByCharacteristicTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipByCharacteristicTest", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestRequestBody Body;
        
        public ShipByCharacteristicTestRequest() {
        }
        
        public ShipByCharacteristicTestRequest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipByCharacteristicTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shipType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string shipSubType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hullNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string engineFuel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string engineNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string maxLengthFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string maxLengthTo;
        
        public ShipByCharacteristicTestRequestBody() {
        }
        
        public ShipByCharacteristicTestRequestBody(string shipType, string shipSubType, string hullNumber, string engineFuel, string engineNumber, string maxLengthFrom, string maxLengthTo) {
            this.shipType = shipType;
            this.shipSubType = shipSubType;
            this.hullNumber = hullNumber;
            this.engineFuel = engineFuel;
            this.engineNumber = engineNumber;
            this.maxLengthFrom = maxLengthFrom;
            this.maxLengthTo = maxLengthTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipByCharacteristicTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipByCharacteristicTestResponse", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestResponseBody Body;
        
        public ShipByCharacteristicTestResponse() {
        }
        
        public ShipByCharacteristicTestResponse(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipByCharacteristicTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipByCharacteristicTestResult;
        
        public ShipByCharacteristicTestResponseBody() {
        }
        
        public ShipByCharacteristicTestResponseBody(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipByCharacteristicTestResult) {
            this.ShipByCharacteristicTestResult = ShipByCharacteristicTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipByCharacteristicsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipByCharacteristics", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsRequestBody Body;
        
        public ShipByCharacteristicsRequest() {
        }
        
        public ShipByCharacteristicsRequest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipByCharacteristicsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<int> shipType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.Nullable<int> shipSubType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hullNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<int> engineFuel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string engineNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<decimal> maxLengthFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> maxLengthTo;
        
        public ShipByCharacteristicsRequestBody() {
        }
        
        public ShipByCharacteristicsRequestBody(System.Nullable<int> shipType, System.Nullable<int> shipSubType, string hullNumber, System.Nullable<int> engineFuel, string engineNumber, System.Nullable<decimal> maxLengthFrom, System.Nullable<decimal> maxLengthTo) {
            this.shipType = shipType;
            this.shipSubType = shipSubType;
            this.hullNumber = hullNumber;
            this.engineFuel = engineFuel;
            this.engineNumber = engineNumber;
            this.maxLengthFrom = maxLengthFrom;
            this.maxLengthTo = maxLengthTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShipByCharacteristicsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShipByCharacteristicsResponse", Namespace="http://marad.bg/", Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsResponseBody Body;
        
        public ShipByCharacteristicsResponse() {
        }
        
        public ShipByCharacteristicsResponse(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://marad.bg/")]
    public partial class ShipByCharacteristicsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipByCharacteristicsResult;
        
        public ShipByCharacteristicsResponseBody() {
        }
        
        public ShipByCharacteristicsResponseBody(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipByCharacteristicsResult) {
            this.ShipByCharacteristicsResult = ShipByCharacteristicsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GovServiceReportSoapChannel : TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GovServiceReportSoapClient : System.ServiceModel.ClientBase<TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap>, TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap {
        
        public GovServiceReportSoapClient() {
        }
        
        public GovServiceReportSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GovServiceReportSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GovServiceReportSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GovServiceReportSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerResponse TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap.ShipsByOwner(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerRequest request) {
            return base.Channel.ShipsByOwner(request);
        }
        
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipsByOwner(string egn) {
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerRequest inValue = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerRequest();
            inValue.Body = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerRequestBody();
            inValue.Body.egn = egn;
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipsByOwnerResponse retVal = ((TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap)(this)).ShipsByOwner(inValue);
            return retVal.Body.ShipsByOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeResponse TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap.ShipType(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeRequest request) {
            return base.Channel.ShipType(request);
        }
        
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] ShipType() {
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeRequest inValue = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeRequest();
            inValue.Body = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeRequestBody();
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipTypeResponse retVal = ((TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap)(this)).ShipType(inValue);
            return retVal.Body.ShipTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeResponse TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap.ShipSubType(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeRequest request) {
            return base.Channel.ShipSubType(request);
        }
        
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] ShipSubType() {
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeRequest inValue = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeRequest();
            inValue.Body = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeRequestBody();
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipSubTypeResponse retVal = ((TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap)(this)).ShipSubType(inValue);
            return retVal.Body.ShipSubTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelResponse TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap.EngineFuel(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelRequest request) {
            return base.Channel.EngineFuel(request);
        }
        
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.Nomenclature[] EngineFuel() {
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelRequest inValue = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelRequest();
            inValue.Body = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelRequestBody();
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.EngineFuelResponse retVal = ((TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap)(this)).EngineFuel(inValue);
            return retVal.Body.EngineFuelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestResponse TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap.ShipByCharacteristicTest(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestRequest request) {
            return base.Channel.ShipByCharacteristicTest(request);
        }
        
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipByCharacteristicTest(string shipType, string shipSubType, string hullNumber, string engineFuel, string engineNumber, string maxLengthFrom, string maxLengthTo) {
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestRequest inValue = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestRequest();
            inValue.Body = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestRequestBody();
            inValue.Body.shipType = shipType;
            inValue.Body.shipSubType = shipSubType;
            inValue.Body.hullNumber = hullNumber;
            inValue.Body.engineFuel = engineFuel;
            inValue.Body.engineNumber = engineNumber;
            inValue.Body.maxLengthFrom = maxLengthFrom;
            inValue.Body.maxLengthTo = maxLengthTo;
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicTestResponse retVal = ((TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap)(this)).ShipByCharacteristicTest(inValue);
            return retVal.Body.ShipByCharacteristicTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsResponse TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap.ShipByCharacteristics(TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsRequest request) {
            return base.Channel.ShipByCharacteristics(request);
        }
        
        public TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovReportShip[] ShipByCharacteristics(System.Nullable<int> shipType, System.Nullable<int> shipSubType, string hullNumber, System.Nullable<int> engineFuel, string engineNumber, System.Nullable<decimal> maxLengthFrom, System.Nullable<decimal> maxLengthTo) {
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsRequest inValue = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsRequest();
            inValue.Body = new TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsRequestBody();
            inValue.Body.shipType = shipType;
            inValue.Body.shipSubType = shipSubType;
            inValue.Body.hullNumber = hullNumber;
            inValue.Body.engineFuel = engineFuel;
            inValue.Body.engineNumber = engineNumber;
            inValue.Body.maxLengthFrom = maxLengthFrom;
            inValue.Body.maxLengthTo = maxLengthTo;
            TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.ShipByCharacteristicsResponse retVal = ((TechnoLogica.RegiX.IAMAVesselsAdapter.VesselsReportService.GovServiceReportSoap)(this)).ShipByCharacteristics(inValue);
            return retVal.Body.ShipByCharacteristicsResult;
        }
    }
}
