// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.29648
//    <NameSpace>TechnoLogica.RegiX.DaeuReportsAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>True</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.DaeuReportsAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    /// <summary>
    /// Справка за извършвани търсения по идентификатор и период - резултат
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29648")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/DaeuReports/SearchByIdentifierResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/DaeuReports/SearchByIdentifierResponse", IsNullable=false)]
    [System.ComponentModel.DescriptionAttribute("Справка за извършвани търсения по идентификатор и период - резултат")]
    public partial class SearchByIdentifierResponse {
        
        private int maxAllowedResultsField;
        
        private long totalResultsField;
        
        private List<ExecutedCallType> executedCallsField;
        
        /// <summary>
        /// SearchByIdentifierResponse class constructor
        /// </summary>
        public SearchByIdentifierResponse() {
            this.executedCallsField = new List<ExecutedCallType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MaxAllowedResults {
            get {
                return this.maxAllowedResultsField;
            }
            set {
                this.maxAllowedResultsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long TotalResults {
            get {
                return this.totalResultsField;
            }
            set {
                this.totalResultsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ExecutedCalls", Order=2)]
        public List<ExecutedCallType> ExecutedCalls {
            get {
                return this.executedCallsField;
            }
            set {
                this.executedCallsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.29648")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/DaeuReports/SearchByIdentifierResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/DaeuReports/SearchByIdentifierResponse", IsNullable=true)]
    public partial class ExecutedCallType {
        
        private decimal apiServiceCallIDField;
        
        private System.DateTime startTimeField;
        
        private string reportNameField;
        
        private string lawReasonField;
        
        private string consumerField;
        
        private string consumerAdministrationField;
        
        private string producerField;
        
        private string producerAdministrationField;
        
        /// <summary>
        /// Номер
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Номер")]
        public decimal ApiServiceCallID {
            get {
                return this.apiServiceCallIDField;
            }
            set {
                this.apiServiceCallIDField = value;
            }
        }
        
        /// <summary>
        /// Дата на извършване на справката
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Дата на извършване на справката")]
        public System.DateTime StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <summary>
        /// Справка
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Справка")]
        public string ReportName {
            get {
                return this.reportNameField;
            }
            set {
                this.reportNameField = value;
            }
        }
        
        /// <summary>
        /// Правно основание
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Правно основание")]
        public string LawReason {
            get {
                return this.lawReasonField;
            }
            set {
                this.lawReasonField = value;
            }
        }
        
        /// <summary>
        /// Консуматор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Консуматор")]
        public string Consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
            }
        }
        
        /// <summary>
        /// Администрация на консуматор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Администрация на консуматор")]
        public string ConsumerAdministration {
            get {
                return this.consumerAdministrationField;
            }
            set {
                this.consumerAdministrationField = value;
            }
        }
        
        /// <summary>
        /// Система/Регистър
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Система/Регистър")]
        public string Producer {
            get {
                return this.producerField;
            }
            set {
                this.producerField = value;
            }
        }
        
        /// <summary>
        /// Първичен администратор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Първичен администратор")]
        public string ProducerAdministration {
            get {
                return this.producerAdministrationField;
            }
            set {
                this.producerAdministrationField = value;
            }
        }
    }
}
