<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:common="http://egov.bg/RegiX/IAOS/REG35Reg/Common" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:n1="http://egov.bg/RegiX/IAOS/REG35Reg/StageInfoByWasteCodeResponse" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<h2 align="center">
						<span>
							<xsl:text>Справка за извличане на информация за площадки по операция с отпадък в Регистър на разрешенията по чл. 67 ЗУО, в т.ч. на тези от тях с прекратено действие.</xsl:text>
						</span>
					</h2>
					<br/>
					<br/>
					<br/>
					<table style="width:45%; " align="center" border="1">
						<thead>
							<tr>
								<th align="left">
									<span>
										<xsl:text>Регистрационен номер</xsl:text>
									</span>
								</th>
								<th align="left">
									<span>
										<xsl:text>Тип на регистрацията</xsl:text>
									</span>
								</th>
								<th align="left">
									<span>
										<xsl:text>Лице за контакт на площадката</xsl:text>
									</span>
								</th>
								<th align="left">
									<span>
										<xsl:text>Телефон на лицето за контакт на площадката</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="n1:REG35_Stage_Info_By_Waste_Code_Response">
								<xsl:for-each select="n1:Authorization">
									<tr>
										<td>
											<xsl:for-each select="n1:AuthNum">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="n1:AuthType">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="n1:ContactPerson">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="n1:Phone">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
									</tr>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					<table style="width:60%; " align="center" border="0" width="100%">
						<tbody>
							<tr>
								<td style="font-size:larger; " align="center" colspan="2">
									<span style="font-weight:bold; ">
										<xsl:text>Данни за площадката:</xsl:text>
									</span>
								</td>
							</tr>
						</tbody>
					</table>
					<table style="width:30%; " align="center" border="1">
						<thead>
							<tr>
								<th style="vertical-align:top; ">
									<span>
										<xsl:text>StageAddress</xsl:text>
									</span>
								</th>
								<th style="vertical-align:top; ">
									<span>
										<xsl:text>StageNum</xsl:text>
									</span>
								</th>
								<th style="width:50%; ">
									<span>
										<xsl:text>WasteCode</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="n1:REG35_Stage_Info_By_Waste_Code_Response">
								<xsl:for-each select="n1:Authorization">
									<xsl:for-each select="n1:Stage">
										<tr>
											<td style="vertical-align:top; ">
												<xsl:for-each select="common:StageAddress">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td style="vertical-align:top; ">
												<xsl:for-each select="common:StageNum">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td style="width:50%; ">
												<xsl:for-each select="common:WasteCode">
													<xsl:apply-templates/>
													<span>
														<xsl:text>, </xsl:text>
													</span>
												</xsl:for-each>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
