// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.27043
//    <NameSpace>TechnoLogica.RegiX.PropertyRegAdapter</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>True</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace TechnoLogica.RegiX.PropertyRegAdapter {
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PropertyActDetailList {
        
        private List<PropertyActDetail> propertyActDetailField;
        
        /// <summary>
        /// PropertyActDetailList class constructor
        /// </summary>
        public PropertyActDetailList() {
            this.propertyActDetailField = new List<PropertyActDetail>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PropertyActDetail", Order=0)]
        public List<PropertyActDetail> PropertyActDetail {
            get {
                return this.propertyActDetailField;
            }
            set {
                this.propertyActDetailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PropertyActDetail {
        
        private int sequenceField;
        
        private bool sequenceFieldSpecified;
        
        private Act actField;
        
        private string lotPartField;
        
        private string listBookNumberField;
        
        private System.DateTime listBookDateField;
        
        private bool listBookDateFieldSpecified;
        
        /// <summary>
        /// PropertyActDetail class constructor
        /// </summary>
        public PropertyActDetail() {
            this.actField = new Act();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SequenceSpecified {
            get {
                return this.sequenceFieldSpecified;
            }
            set {
                this.sequenceFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Act Act {
            get {
                return this.actField;
            }
            set {
                this.actField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LotPart {
            get {
                return this.lotPartField;
            }
            set {
                this.lotPartField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ListBookNumber {
            get {
                return this.listBookNumberField;
            }
            set {
                this.listBookNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime ListBookDate {
            get {
                return this.listBookDateField;
            }
            set {
                this.listBookDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListBookDateSpecified {
            get {
                return this.listBookDateFieldSpecified;
            }
            set {
                this.listBookDateFieldSpecified = value;
            }
        }
    }
    
    /// <summary>
    /// Данни за акт
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    [System.ComponentModel.DescriptionAttribute("Данни за акт")]
    public partial class Act {
        
        private string incomingRegistrationNumberField;
        
        private System.DateTime incomingRegistrationDateField;
        
        private bool incomingRegistrationDateFieldSpecified;
        
        private string doubleRegisterNumberField;
        
        private System.DateTime registrationDateField;
        
        private bool registrationDateFieldSpecified;
        
        private string bookTypeNameField;
        
        private string actTypeNameField;
        
        private string volumeField;
        
        private int pageField;
        
        private bool pageFieldSpecified;
        
        private string actYearField;
        
        private string conditionField;
        
        private string connectedActsField;
        
        private ActLeftSide leftSideField;
        
        private ActRightSide rightSideField;
        
        /// <summary>
        /// Act class constructor
        /// </summary>
        public Act() {
            this.rightSideField = new ActRightSide();
            this.leftSideField = new ActLeftSide();
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string IncomingRegistrationNumber {
            get {
                return this.incomingRegistrationNumberField;
            }
            set {
                this.incomingRegistrationNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime IncomingRegistrationDate {
            get {
                return this.incomingRegistrationDateField;
            }
            set {
                this.incomingRegistrationDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncomingRegistrationDateSpecified {
            get {
                return this.incomingRegistrationDateFieldSpecified;
            }
            set {
                this.incomingRegistrationDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DoubleRegisterNumber {
            get {
                return this.doubleRegisterNumberField;
            }
            set {
                this.doubleRegisterNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationDateSpecified {
            get {
                return this.registrationDateFieldSpecified;
            }
            set {
                this.registrationDateFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BookTypeName {
            get {
                return this.bookTypeNameField;
            }
            set {
                this.bookTypeNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ActTypeName {
            get {
                return this.actTypeNameField;
            }
            set {
                this.actTypeNameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageSpecified {
            get {
                return this.pageFieldSpecified;
            }
            set {
                this.pageFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ActYear {
            get {
                return this.actYearField;
            }
            set {
                this.actYearField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ConnectedActs {
            get {
                return this.connectedActsField;
            }
            set {
                this.connectedActsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public ActLeftSide LeftSide {
            get {
                return this.leftSideField;
            }
            set {
                this.leftSideField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public ActRightSide RightSide {
            get {
                return this.rightSideField;
            }
            set {
                this.rightSideField = value;
            }
        }
    }
    
    /// <summary>
    /// Страни - ляво
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.ComponentModel.DescriptionAttribute("Страни - ляво")]
    public partial class ActLeftSide {
        
        private List<string> sideField;
        
        /// <summary>
        /// ActLeftSide class constructor
        /// </summary>
        public ActLeftSide() {
            this.sideField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Side", Order=0)]
        public List<string> Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
    }
    
    /// <summary>
    /// Страни - дясно
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.ComponentModel.DescriptionAttribute("Страни - дясно")]
    public partial class ActRightSide {
        
        private List<string> sideField;
        
        /// <summary>
        /// ActRightSide class constructor
        /// </summary>
        public ActRightSide() {
            this.sideField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Side", Order=0)]
        public List<string> Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PropertyActDetailListV2 {
        
        private List<PropertyActDetailV2> propertyActDetailField;
        
        /// <summary>
        /// PropertyActDetailListV2 class constructor
        /// </summary>
        public PropertyActDetailListV2() {
            this.propertyActDetailField = new List<PropertyActDetailV2>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PropertyActDetail", Order=0)]
        public List<PropertyActDetailV2> PropertyActDetail {
            get {
                return this.propertyActDetailField;
            }
            set {
                this.propertyActDetailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PropertyActDetailV2 {
        
        private int sequenceField;
        
        private bool sequenceFieldSpecified;
        
        private ActV2 actField;
        
        private string lotPartField;
        
        private string listBookNumberField;
        
        private System.DateTime listBookDateField;
        
        private bool listBookDateFieldSpecified;
        
        /// <summary>
        /// PropertyActDetailV2 class constructor
        /// </summary>
        public PropertyActDetailV2() {
            this.actField = new ActV2();
        }
        
        /// <summary>
        /// Пореден номер в справката
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Пореден номер в справката")]
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SequenceSpecified {
            get {
                return this.sequenceFieldSpecified;
            }
            set {
                this.sequenceFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Данни за акт
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Данни за акт")]
        public ActV2 Act {
            get {
                return this.actField;
            }
            set {
                this.actField = value;
            }
        }
        
        /// <summary>
        /// Част от партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Част от партида")]
        public string LotPart {
            get {
                return this.lotPartField;
            }
            set {
                this.lotPartField = value;
            }
        }
        
        /// <summary>
        /// № от описна книга
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("№ от описна книга")]
        public string ListBookNumber {
            get {
                return this.listBookNumberField;
            }
            set {
                this.listBookNumberField = value;
            }
        }
        
        /// <summary>
        /// Дата от описна книга
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Дата от описна книга")]
        public System.DateTime ListBookDate {
            get {
                return this.listBookDateField;
            }
            set {
                this.listBookDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListBookDateSpecified {
            get {
                return this.listBookDateFieldSpecified;
            }
            set {
                this.listBookDateFieldSpecified = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class ActV2 {
        
        private string incomingRegistrationNumberField;
        
        private System.DateTime incomingRegistrationDateField;
        
        private bool incomingRegistrationDateFieldSpecified;
        
        private string doubleRegisterNumberField;
        
        private System.DateTime registrationDateField;
        
        private bool registrationDateFieldSpecified;
        
        private string bookTypeNameField;
        
        private string actTypeNameField;
        
        private string volumeField;
        
        private int pageField;
        
        private bool pageFieldSpecified;
        
        private string actYearField;
        
        private string conditionField;
        
        private string connectedActsField;
        
        private ActV2LeftSide leftSideField;
        
        private ActV2RightSide rightSideField;
        
        private decimal worthValueField;
        
        private bool worthValueFieldSpecified;
        
        private string worthCurrencyField;
        
        /// <summary>
        /// ActV2 class constructor
        /// </summary>
        public ActV2() {
            this.rightSideField = new ActV2RightSide();
            this.leftSideField = new ActV2LeftSide();
        }
        
        /// <summary>
        /// Номер от входящ рег
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Номер от входящ рег")]
        public string IncomingRegistrationNumber {
            get {
                return this.incomingRegistrationNumberField;
            }
            set {
                this.incomingRegistrationNumberField = value;
            }
        }
        
        /// <summary>
        /// Дата от входящ рег
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Дата от входящ рег")]
        public System.DateTime IncomingRegistrationDate {
            get {
                return this.incomingRegistrationDateField;
            }
            set {
                this.incomingRegistrationDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncomingRegistrationDateSpecified {
            get {
                return this.incomingRegistrationDateFieldSpecified;
            }
            set {
                this.incomingRegistrationDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Номер от дв. вх. рег
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Номер от дв. вх. рег")]
        public string DoubleRegisterNumber {
            get {
                return this.doubleRegisterNumberField;
            }
            set {
                this.doubleRegisterNumberField = value;
            }
        }
        
        /// <summary>
        /// Дата
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Дата")]
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RegistrationDateSpecified {
            get {
                return this.registrationDateFieldSpecified;
            }
            set {
                this.registrationDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Книга
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Книга")]
        public string BookTypeName {
            get {
                return this.bookTypeNameField;
            }
            set {
                this.bookTypeNameField = value;
            }
        }
        
        /// <summary>
        /// Тип акт
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        [System.ComponentModel.DescriptionAttribute("Тип акт")]
        public string ActTypeName {
            get {
                return this.actTypeNameField;
            }
            set {
                this.actTypeNameField = value;
            }
        }
        
        /// <summary>
        /// Акт том
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Акт том")]
        public string Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
        
        /// <summary>
        /// Акт номер
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Акт номер")]
        public int Page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PageSpecified {
            get {
                return this.pageFieldSpecified;
            }
            set {
                this.pageFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Година
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Година")]
        public string ActYear {
            get {
                return this.actYearField;
            }
            set {
                this.actYearField = value;
            }
        }
        
        /// <summary>
        /// Условие
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DescriptionAttribute("Условие")]
        public string Condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <summary>
        /// Свързани актове
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DescriptionAttribute("Свързани актове")]
        public string ConnectedActs {
            get {
                return this.connectedActsField;
            }
            set {
                this.connectedActsField = value;
            }
        }
        
        /// <summary>
        /// Страни - ляво
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Страни - ляво")]
        public ActV2LeftSide LeftSide {
            get {
                return this.leftSideField;
            }
            set {
                this.leftSideField = value;
            }
        }
        
        /// <summary>
        /// Страни - дясно
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DescriptionAttribute("Страни - дясно")]
        public ActV2RightSide RightSide {
            get {
                return this.rightSideField;
            }
            set {
                this.rightSideField = value;
            }
        }
        
        /// <summary>
        /// Стойност на материалния интерес
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DescriptionAttribute("Стойност на материалния интерес")]
        public decimal WorthValue {
            get {
                return this.worthValueField;
            }
            set {
                this.worthValueField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WorthValueSpecified {
            get {
                return this.worthValueFieldSpecified;
            }
            set {
                this.worthValueFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Код на валутата на материалния интерес
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DescriptionAttribute("Код на валутата на материалния интерес")]
        public string WorthCurrency {
            get {
                return this.worthCurrencyField;
            }
            set {
                this.worthCurrencyField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    public partial class ActV2LeftSide {
        
        private List<string> sideField;
        
        /// <summary>
        /// ActV2LeftSide class constructor
        /// </summary>
        public ActV2LeftSide() {
            this.sideField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Side", Order=0)]
        public List<string> Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    public partial class ActV2RightSide {
        
        private List<string> sideField;
        
        /// <summary>
        /// ActV2RightSide class constructor
        /// </summary>
        public ActV2RightSide() {
            this.sideField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Side", Order=0)]
        public List<string> Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class Sides {
        
        private List<SidesSide> sideField;
        
        /// <summary>
        /// Sides class constructor
        /// </summary>
        public Sides() {
            this.sideField = new List<SidesSide>();
        }
        
        /// <summary>
        /// Страна
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("Side", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Страна")]
        public List<SidesSide> Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    public partial class SidesSide {
        
        private int orderNumberField;
        
        private bool orderNumberFieldSpecified;
        
        private string textField;
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderNumberSpecified {
            get {
                return this.orderNumberFieldSpecified;
            }
            set {
                this.orderNumberFieldSpecified = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonalLotEntry {
        
        private Act actField;
        
        private string propertyDataField;
        
        private string lotNumberField;
        
        private string cadastreIdentificatorField;
        
        /// <summary>
        /// PersonalLotEntry class constructor
        /// </summary>
        public PersonalLotEntry() {
            this.actField = new Act();
        }
        
        /// <summary>
        /// Вписване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Вписване")]
        public Act Act {
            get {
                return this.actField;
            }
            set {
                this.actField = value;
            }
        }
        
        /// <summary>
        /// Имот
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Имот")]
        public string PropertyData {
            get {
                return this.propertyDataField;
            }
            set {
                this.propertyDataField = value;
            }
        }
        
        /// <summary>
        /// Партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Партида")]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <summary>
        /// Кадастрален идентификатор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Кадастрален идентификатор")]
        public string CadastreIdentificator {
            get {
                return this.cadastreIdentificatorField;
            }
            set {
                this.cadastreIdentificatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonalLotEntryV2 {
        
        private ActV2 actField;
        
        private string propertyDataField;
        
        private string lotNumberField;
        
        private string cadastreIdentificatorField;
        
        /// <summary>
        /// PersonalLotEntryV2 class constructor
        /// </summary>
        public PersonalLotEntryV2() {
            this.actField = new ActV2();
        }
        
        /// <summary>
        /// Вписване
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Вписване")]
        public ActV2 Act {
            get {
                return this.actField;
            }
            set {
                this.actField = value;
            }
        }
        
        /// <summary>
        /// Имот
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Имот")]
        public string PropertyData {
            get {
                return this.propertyDataField;
            }
            set {
                this.propertyDataField = value;
            }
        }
        
        /// <summary>
        /// Партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Партида")]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <summary>
        /// Кадастрален идентификатор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Кадастрален идентификатор")]
        public string CadastreIdentificator {
            get {
                return this.cadastreIdentificatorField;
            }
            set {
                this.cadastreIdentificatorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonalLotEntryList {
        
        private List<PersonalLotEntry> personalLotEntryField;
        
        /// <summary>
        /// PersonalLotEntryList class constructor
        /// </summary>
        public PersonalLotEntryList() {
            this.personalLotEntryField = new List<PersonalLotEntry>();
        }
        
        /// <summary>
        /// Запис персонална партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PersonalLotEntry", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Запис персонална партида")]
        public List<PersonalLotEntry> PersonalLotEntry {
            get {
                return this.personalLotEntryField;
            }
            set {
                this.personalLotEntryField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonalLotEntryListV2 {
        
        private List<PersonalLotEntryV2> personalLotEntryField;
        
        /// <summary>
        /// PersonalLotEntryListV2 class constructor
        /// </summary>
        public PersonalLotEntryListV2() {
            this.personalLotEntryField = new List<PersonalLotEntryV2>();
        }
        
        /// <summary>
        /// Запис персонална партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("PersonalLotEntry", Order=0)]
        [System.ComponentModel.DescriptionAttribute("Запис персонална партида")]
        public List<PersonalLotEntryV2> PersonalLotEntry {
            get {
                return this.personalLotEntryField;
            }
            set {
                this.personalLotEntryField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonLotData {
        
        private string registryAgencyField;
        
        private string siteIDField;
        
        private System.DateTime siteStartDateField;
        
        private bool siteStartDateFieldSpecified;
        
        private string personBasicDataField;
        
        private string personalLotNumberField;
        
        private List<PersonalLotEntry> personalLotEntryListField;
        
        /// <summary>
        /// PersonLotData class constructor
        /// </summary>
        public PersonLotData() {
            this.personalLotEntryListField = new List<PersonalLotEntry>();
        }
        
        /// <summary>
        /// Служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Служба по вписвания")]
        public string RegistryAgency {
            get {
                return this.registryAgencyField;
            }
            set {
                this.registryAgencyField = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на служба по вписвания")]
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <summary>
        /// Година на стартиране на информационна система
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        [System.ComponentModel.DescriptionAttribute("Година на стартиране на информационна система")]
        public System.DateTime SiteStartDate {
            get {
                return this.siteStartDateField;
            }
            set {
                this.siteStartDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiteStartDateSpecified {
            get {
                return this.siteStartDateFieldSpecified;
            }
            set {
                this.siteStartDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Имена и ЕГН
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Имена и ЕГН")]
        public string PersonBasicData {
            get {
                return this.personBasicDataField;
            }
            set {
                this.personBasicDataField = value;
            }
        }
        
        /// <summary>
        /// Персонална партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Персонална партида")]
        public string PersonalLotNumber {
            get {
                return this.personalLotNumberField;
            }
            set {
                this.personalLotNumberField = value;
            }
        }
        
        /// <summary>
        /// Вписвания за конкретна партида на лицато
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        [System.ComponentModel.DescriptionAttribute("Вписвания за конкретна партида на лицато")]
        public List<PersonalLotEntry> PersonalLotEntryList {
            get {
                return this.personalLotEntryListField;
            }
            set {
                this.personalLotEntryListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonLotDataV2 {
        
        private string registryAgencyField;
        
        private string siteIDField;
        
        private System.DateTime siteStartDateField;
        
        private bool siteStartDateFieldSpecified;
        
        private string personBasicDataField;
        
        private string personalLotNumberField;
        
        private List<PersonalLotEntryV2> personalLotEntryListField;
        
        /// <summary>
        /// PersonLotDataV2 class constructor
        /// </summary>
        public PersonLotDataV2() {
            this.personalLotEntryListField = new List<PersonalLotEntryV2>();
        }
        
        /// <summary>
        /// Служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Служба по вписвания")]
        public string RegistryAgency {
            get {
                return this.registryAgencyField;
            }
            set {
                this.registryAgencyField = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на служба по вписвания")]
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <summary>
        /// Година на стартиране на информационна система
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        [System.ComponentModel.DescriptionAttribute("Година на стартиране на информационна система")]
        public System.DateTime SiteStartDate {
            get {
                return this.siteStartDateField;
            }
            set {
                this.siteStartDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiteStartDateSpecified {
            get {
                return this.siteStartDateFieldSpecified;
            }
            set {
                this.siteStartDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Имена и ЕГН
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Имена и ЕГН")]
        public string PersonBasicData {
            get {
                return this.personBasicDataField;
            }
            set {
                this.personBasicDataField = value;
            }
        }
        
        /// <summary>
        /// Персонална партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Персонална партида")]
        public string PersonalLotNumber {
            get {
                return this.personalLotNumberField;
            }
            set {
                this.personalLotNumberField = value;
            }
        }
        
        /// <summary>
        /// Вписвания за конкретна партида на лицато
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PersonalLotEntry", IsNullable=false)]
        [System.ComponentModel.DescriptionAttribute("Вписвания за конкретна партида на лицато")]
        public List<PersonalLotEntryV2> PersonalLotEntryList {
            get {
                return this.personalLotEntryListField;
            }
            set {
                this.personalLotEntryListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class EntityLotData {
        
        private string registryAgencyField;
        
        private string siteIDField;
        
        private System.DateTime siteStartDateField;
        
        private bool siteStartDateFieldSpecified;
        
        private string entityBasicDataField;
        
        private string personalLotNumberField;
        
        private List<PersonalLotEntry> personalLotEntryListField;
        
        /// <summary>
        /// EntityLotData class constructor
        /// </summary>
        public EntityLotData() {
            this.personalLotEntryListField = new List<PersonalLotEntry>();
        }
        
        /// <summary>
        /// Служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Служба по вписвания")]
        public string RegistryAgency {
            get {
                return this.registryAgencyField;
            }
            set {
                this.registryAgencyField = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на служба по вписвания")]
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <summary>
        /// Година на стартиране на информационна система
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        [System.ComponentModel.DescriptionAttribute("Година на стартиране на информационна система")]
        public System.DateTime SiteStartDate {
            get {
                return this.siteStartDateField;
            }
            set {
                this.siteStartDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiteStartDateSpecified {
            get {
                return this.siteStartDateFieldSpecified;
            }
            set {
                this.siteStartDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Име и ЕИК
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Име и ЕИК")]
        public string EntityBasicData {
            get {
                return this.entityBasicDataField;
            }
            set {
                this.entityBasicDataField = value;
            }
        }
        
        /// <summary>
        /// Персонална партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Персонална партида")]
        public string PersonalLotNumber {
            get {
                return this.personalLotNumberField;
            }
            set {
                this.personalLotNumberField = value;
            }
        }
        
        /// <summary>
        /// Вписвания за конкретна партида на лицето
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        [System.ComponentModel.DescriptionAttribute("Вписвания за конкретна партида на лицето")]
        public List<PersonalLotEntry> PersonalLotEntryList {
            get {
                return this.personalLotEntryListField;
            }
            set {
                this.personalLotEntryListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class EntityLotDataV2 {
        
        private string registryAgencyField;
        
        private string siteIDField;
        
        private System.DateTime siteStartDateField;
        
        private bool siteStartDateFieldSpecified;
        
        private string entityBasicDataField;
        
        private string personalLotNumberField;
        
        private List<PersonalLotEntryV2> personalLotEntryListField;
        
        /// <summary>
        /// EntityLotDataV2 class constructor
        /// </summary>
        public EntityLotDataV2() {
            this.personalLotEntryListField = new List<PersonalLotEntryV2>();
        }
        
        /// <summary>
        /// Служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Служба по вписвания")]
        public string RegistryAgency {
            get {
                return this.registryAgencyField;
            }
            set {
                this.registryAgencyField = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на служба по вписвания")]
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <summary>
        /// Година на стартиране на информационна система
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        [System.ComponentModel.DescriptionAttribute("Година на стартиране на информационна система")]
        public System.DateTime SiteStartDate {
            get {
                return this.siteStartDateField;
            }
            set {
                this.siteStartDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiteStartDateSpecified {
            get {
                return this.siteStartDateFieldSpecified;
            }
            set {
                this.siteStartDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Име и ЕИК
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Име и ЕИК")]
        public string EntityBasicData {
            get {
                return this.entityBasicDataField;
            }
            set {
                this.entityBasicDataField = value;
            }
        }
        
        /// <summary>
        /// Персонална партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Персонална партида")]
        public string PersonalLotNumber {
            get {
                return this.personalLotNumberField;
            }
            set {
                this.personalLotNumberField = value;
            }
        }
        
        /// <summary>
        /// Вписвания за конкретна партида на лицето
        /// </summary>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PersonalLotEntry", IsNullable=false)]
        [System.ComponentModel.DescriptionAttribute("Вписвания за конкретна партида на лицето")]
        public List<PersonalLotEntryV2> PersonalLotEntryList {
            get {
                return this.personalLotEntryListField;
            }
            set {
                this.personalLotEntryListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonLotDataList {
        
        private List<PersonLotData> personLotDataField;
        
        /// <summary>
        /// PersonLotDataList class constructor
        /// </summary>
        public PersonLotDataList() {
            this.personLotDataField = new List<PersonLotData>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PersonLotData", Order=0)]
        public List<PersonLotData> PersonLotData {
            get {
                return this.personLotDataField;
            }
            set {
                this.personLotDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PersonLotDataListV2 {
        
        private List<PersonLotDataV2> personLotDataField;
        
        /// <summary>
        /// PersonLotDataListV2 class constructor
        /// </summary>
        public PersonLotDataListV2() {
            this.personLotDataField = new List<PersonLotDataV2>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PersonLotData", Order=0)]
        public List<PersonLotDataV2> PersonLotData {
            get {
                return this.personLotDataField;
            }
            set {
                this.personLotDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class EntityLotDataList {
        
        private List<EntityLotData> entityLotDataField;
        
        /// <summary>
        /// EntityLotDataList class constructor
        /// </summary>
        public EntityLotDataList() {
            this.entityLotDataField = new List<EntityLotData>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EntityLotData", Order=0)]
        public List<EntityLotData> EntityLotData {
            get {
                return this.entityLotDataField;
            }
            set {
                this.entityLotDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class EntityLotDataListV2 {
        
        private List<EntityLotDataV2> entityLotDataField;
        
        /// <summary>
        /// EntityLotDataListV2 class constructor
        /// </summary>
        public EntityLotDataListV2() {
            this.entityLotDataField = new List<EntityLotDataV2>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EntityLotData", Order=0)]
        public List<EntityLotDataV2> EntityLotData {
            get {
                return this.entityLotDataField;
            }
            set {
                this.entityLotDataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PropertyDetail {
        
        private string propertyIDField;
        
        private string lotNumberField;
        
        private string oldLotNumberField;
        
        private string registryAgencyField;
        
        private string siteIDField;
        
        private System.DateTime siteStartDateField;
        
        private bool siteStartDateFieldSpecified;
        
        private string cadastreNumberField;
        
        private string secondCadastreNumberField;
        
        private string propertyTypeField;
        
        private string districtNameField;
        
        private string municipalityNameField;
        
        private string territorialUnitNameField;
        
        private string housingEstateField;
        
        private string neighborhoodNameField;
        
        private string streetNameField;
        
        private string streetNumberField;
        
        private string blockField;
        
        private string entranceField;
        
        private string floorField;
        
        private string appartmentField;
        
        private string postBoxField;
        
        private string remarkField;
        
        /// <summary>
        /// Системен идентификатор на имот
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        [System.ComponentModel.DescriptionAttribute("Системен идентификатор на имот")]
        public string PropertyID {
            get {
                return this.propertyIDField;
            }
            set {
                this.propertyIDField = value;
            }
        }
        
        /// <summary>
        /// Партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.ComponentModel.DescriptionAttribute("Партида")]
        public string LotNumber {
            get {
                return this.lotNumberField;
            }
            set {
                this.lotNumberField = value;
            }
        }
        
        /// <summary>
        /// Стара партида
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.ComponentModel.DescriptionAttribute("Стара партида")]
        public string OldLotNumber {
            get {
                return this.oldLotNumberField;
            }
            set {
                this.oldLotNumberField = value;
            }
        }
        
        /// <summary>
        /// Служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        [System.ComponentModel.DescriptionAttribute("Служба по вписвания")]
        public string RegistryAgency {
            get {
                return this.registryAgencyField;
            }
            set {
                this.registryAgencyField = value;
            }
        }
        
        /// <summary>
        /// Идентификатор на служба по вписвания
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        [System.ComponentModel.DescriptionAttribute("Идентификатор на служба по вписвания")]
        public string SiteID {
            get {
                return this.siteIDField;
            }
            set {
                this.siteIDField = value;
            }
        }
        
        /// <summary>
        /// Година на стартиране на информационна система
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        [System.ComponentModel.DescriptionAttribute("Година на стартиране на информационна система")]
        public System.DateTime SiteStartDate {
            get {
                return this.siteStartDateField;
            }
            set {
                this.siteStartDateField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SiteStartDateSpecified {
            get {
                return this.siteStartDateFieldSpecified;
            }
            set {
                this.siteStartDateFieldSpecified = value;
            }
        }
        
        /// <summary>
        /// Кадастрален идентификатор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.ComponentModel.DescriptionAttribute("Кадастрален идентификатор")]
        public string CadastreNumber {
            get {
                return this.cadastreNumberField;
            }
            set {
                this.cadastreNumberField = value;
            }
        }
        
        /// <summary>
        /// Втори кадастрален идентификатор
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        [System.ComponentModel.DescriptionAttribute("Втори кадастрален идентификатор")]
        public string SecondCadastreNumber {
            get {
                return this.secondCadastreNumberField;
            }
            set {
                this.secondCadastreNumberField = value;
            }
        }
        
        /// <summary>
        /// Вид на имот
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        [System.ComponentModel.DescriptionAttribute("Вид на имот")]
        public string PropertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
            }
        }
        
        /// <summary>
        /// Наименование на област
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        [System.ComponentModel.DescriptionAttribute("Наименование на област")]
        public string DistrictName {
            get {
                return this.districtNameField;
            }
            set {
                this.districtNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на община
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        [System.ComponentModel.DescriptionAttribute("Наименование на община")]
        public string MunicipalityName {
            get {
                return this.municipalityNameField;
            }
            set {
                this.municipalityNameField = value;
            }
        }
        
        /// <summary>
        /// Наименование на населено място
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        [System.ComponentModel.DescriptionAttribute("Наименование на населено място")]
        public string TerritorialUnitName {
            get {
                return this.territorialUnitNameField;
            }
            set {
                this.territorialUnitNameField = value;
            }
        }
        
        /// <summary>
        /// Жилищен комплекс
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        [System.ComponentModel.DescriptionAttribute("Жилищен комплекс")]
        public string HousingEstate {
            get {
                return this.housingEstateField;
            }
            set {
                this.housingEstateField = value;
            }
        }
        
        /// <summary>
        /// Квартал
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        [System.ComponentModel.DescriptionAttribute("Квартал")]
        public string NeighborhoodName {
            get {
                return this.neighborhoodNameField;
            }
            set {
                this.neighborhoodNameField = value;
            }
        }
        
        /// <summary>
        /// Улица
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        [System.ComponentModel.DescriptionAttribute("Улица")]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <summary>
        /// Номер на улица
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        [System.ComponentModel.DescriptionAttribute("Номер на улица")]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
            }
        }
        
        /// <summary>
        /// Блок
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        [System.ComponentModel.DescriptionAttribute("Блок")]
        public string Block {
            get {
                return this.blockField;
            }
            set {
                this.blockField = value;
            }
        }
        
        /// <summary>
        /// Вход
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        [System.ComponentModel.DescriptionAttribute("Вход")]
        public string Entrance {
            get {
                return this.entranceField;
            }
            set {
                this.entranceField = value;
            }
        }
        
        /// <summary>
        /// Етаж
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        [System.ComponentModel.DescriptionAttribute("Етаж")]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <summary>
        /// Апартамент
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        [System.ComponentModel.DescriptionAttribute("Апартамент")]
        public string Appartment {
            get {
                return this.appartmentField;
            }
            set {
                this.appartmentField = value;
            }
        }
        
        /// <summary>
        /// Пощенска кутия
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        [System.ComponentModel.DescriptionAttribute("Пощенска кутия")]
        public string PostBox {
            get {
                return this.postBoxField;
            }
            set {
                this.postBoxField = value;
            }
        }
        
        /// <summary>
        /// Описание
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        [System.ComponentModel.DescriptionAttribute("Описание")]
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.4.0.17088")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://egov.bg/RegiX/AV/PropertyReg", IsNullable=true)]
    public partial class PropertyDetailList {
        
        private List<PropertyDetail> propertyDetailField;
        
        /// <summary>
        /// PropertyDetailList class constructor
        /// </summary>
        public PropertyDetailList() {
            this.propertyDetailField = new List<PropertyDetail>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PropertyDetail", Order=0)]
        public List<PropertyDetail> PropertyDetail {
            get {
                return this.propertyDetailField;
            }
            set {
                this.propertyDetailField = value;
            }
        }
    }
}
