<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2008 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:impl="http://egov.bg/RegiX/MT/TOTAByEIKResponse" xmlns:xdt="http://www.w3.org/2005/xpath-datatypes" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.0 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML" select="/"/>
	<xsl:decimal-format name="format1" grouping-separator=" " decimal-separator=","/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
			</head>
			<body>
				<xsl:for-each select="$XML">
					<br/>
					<br/>
					<table style="width:70%; " align="center" border="0" width="100%">
						<tbody>
							<tr>
								<td align="left">
									<span style="font-weight:bold; ">
										<xsl:text>ЕИК: </xsl:text>
									</span>
								</td>
								<td align="center">
									<xsl:for-each select="impl:TOTAByEIKResponse">
										<xsl:for-each select="EIK">
											<xsl:apply-templates/>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
							<tr>
								<td align="left">
									<span style="font-weight:bold; ">
										<xsl:text>Наименование на юридическото лице:</xsl:text>
									</span>
								</td>
								<td align="center">
									<xsl:for-each select="impl:TOTAByEIKResponse">
										<xsl:for-each select="CompanyName">
											<xsl:apply-templates/>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
							<tr>
								<td align="left">
									<span style="font-weight:bold; ">
										<xsl:text>Вид туристическа дейност: </xsl:text>
									</span>
								</td>
								<td align="center">
									<xsl:for-each select="impl:TOTAByEIKResponse">
										<xsl:for-each select="TourOperationType">
											<xsl:apply-templates/>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
							<tr>
								<td align="left">
									<span style="font-weight:bold; ">
										<xsl:text>Регистрационен номер: </xsl:text>
									</span>
								</td>
								<td align="center">
									<xsl:for-each select="impl:TOTAByEIKResponse">
										<xsl:for-each select="Registration">
											<xsl:for-each select="RegNum">
												<xsl:apply-templates/>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
							<tr>
								<td align="left">
									<span style="font-weight:bold; ">
										<xsl:text>Дата на заповед за регистрация: </xsl:text>
									</span>
								</td>
								<td align="center">
									<xsl:for-each select="impl:TOTAByEIKResponse">
										<xsl:for-each select="Registration">
											<xsl:for-each select="DateIssued">
												<span>
													<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
													<xsl:text>.</xsl:text>
													<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
													<xsl:text>.</xsl:text>
													<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
												</span>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
							<tr>
								<td align="left">
									<span style="font-weight:bold; ">
										<xsl:text>Номер на заповед: </xsl:text>
									</span>
								</td>
								<td align="center">
									<xsl:for-each select="impl:TOTAByEIKResponse">
										<xsl:for-each select="Registration">
											<xsl:for-each select="Order">
												<xsl:for-each select="Number">
													<xsl:apply-templates/>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
							<tr>
								<td align="left">
									<span style="font-weight:bold; ">
										<xsl:text>Дата:</xsl:text>
									</span>
								</td>
								<td align="center">
									<xsl:for-each select="impl:TOTAByEIKResponse">
										<xsl:for-each select="Registration">
											<xsl:for-each select="Order">
												<xsl:for-each select="Date">
													<span>
														<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00', 'format1')"/>
														<xsl:text>.</xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00', 'format1')"/>
														<xsl:text>.</xsl:text>
														<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000', 'format1')"/>
													</span>
												</xsl:for-each>
											</xsl:for-each>
										</xsl:for-each>
									</xsl:for-each>
								</td>
							</tr>
						</tbody>
					</table>
					<br/>
					<h4 style="padding-left:5%; " align="center">
						<span style="font-weight:bold; ">
							<xsl:text>Заповед за промяна: </xsl:text>
						</span>
					</h4>
					<table style="width:70%; " align="center" border="1">
						<thead>
							<tr>
								<th align="center">
									<span>
										<xsl:text>Номер на заповед за промяна</xsl:text>
									</span>
								</th>
								<th align="center">
									<span>
										<xsl:text>Дата</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="impl:TOTAByEIKResponse">
								<xsl:for-each select="OrderChanges">
									<xsl:for-each select="OrderChange">
										<tr>
											<td align="center">
												<xsl:for-each select="Number">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td align="center">
												<xsl:for-each select="Date">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					<h4 style="padding-left:5%; " align="center">
						<span style="font-weight:bold; ">
							<xsl:text>Заповед за прекратяване на дейността:</xsl:text>
						</span>
						<span>
							<xsl:text>&#160;</xsl:text>
						</span>
					</h4>
					<table style="width:70%; " align="center" border="1">
						<thead>
							<tr>
								<th align="center">
									<span>
										<xsl:text>Номер на заповед за прекратяване на дейността:</xsl:text>
									</span>
								</th>
								<th align="center">
									<span>
										<xsl:text>Дата на заповед за прекратяване на дейността:</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="impl:TOTAByEIKResponse">
								<xsl:for-each select="LicenseCancellationOrder">
									<tr>
										<td align="center">
											<xsl:for-each select="Number">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td align="center">
											<xsl:for-each select="Date">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
									</tr>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					<h4 style="padding-left:5%; " align="center">
						<span style="font-weight:bold; ">
							<xsl:text>Лиценз: </xsl:text>
						</span>
					</h4>
					<table style="width:70%; " align="center" border="1">
						<thead>
							<tr>
								<th>
									<span>
										<xsl:text>Номер на заповед за издаване на лиценз: </xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Дата на заповед за издаване на лиценз:</xsl:text>
									</span>
								</th>
								<th>
									<span>
										<xsl:text>Заповед</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="impl:TOTAByEIKResponse">
								<xsl:for-each select="License">
									<tr>
										<td>
											<xsl:for-each select="LicenseIssuedOrderNum">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<xsl:for-each select="LicenseIssuedOrderDate">
												<xsl:apply-templates/>
											</xsl:for-each>
										</td>
										<td>
											<table border="1">
												<thead>
													<tr>
														<th>
															<span>
																<xsl:text>Номер</xsl:text>
															</span>
														</th>
														<th>
															<span>
																<xsl:text>Дата</xsl:text>
															</span>
														</th>
													</tr>
												</thead>
												<tbody>
													<xsl:for-each select="Order">
														<tr>
															<td>
																<xsl:for-each select="Number">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
															<td>
																<xsl:for-each select="Date">
																	<xsl:apply-templates/>
																</xsl:for-each>
															</td>
														</tr>
													</xsl:for-each>
												</tbody>
											</table>
										</td>
									</tr>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					<br/>
					<h4 style="padding-left:5%; " align="center">
						<span style="font-weight:bold; ">
							<xsl:text>Офиси:</xsl:text>
						</span>
					</h4>
					<table align="center" border="1">
						<thead>
							<tr>
								<th align="center">
									<span>
										<xsl:text>Град</xsl:text>
									</span>
								</th>
								<th align="center">
									<span>
										<xsl:text>Адрес</xsl:text>
									</span>
								</th>
								<th align="center">
									<span>
										<xsl:text>Телефон</xsl:text>
									</span>
								</th>
							</tr>
						</thead>
						<tbody>
							<xsl:for-each select="impl:TOTAByEIKResponse">
								<xsl:for-each select="Offices">
									<xsl:for-each select="Office">
										<tr>
											<td align="center">
												<xsl:for-each select="OfficePopName">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td align="center">
												<xsl:for-each select="OfficeAddress">
													<xsl:apply-templates/>
												</xsl:for-each>
											</td>
											<td align="center">
												<xsl:for-each select="OfficePhone">
													<p align="center">
														<xsl:apply-templates/>
													</p>
												</xsl:for-each>
											</td>
										</tr>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</tbody>
					</table>
					<br/>
					<br/>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
